<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=561; $k<641; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 561; $ii < 641; $ii++){
    $qry .= "a2.SelectA_".$ii.", a2.TimeA_".$ii.", a2.Confidence_".$ii.", b2.SelectB_".$ii.", b2.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_8 as a2, Data_B_8 as b2 where u.uid = a2.uid and u.uid = b2.uid";
$res = $mysqli->query($qry);

//echo $qry;

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_561."</td>
       <td>".$row->TimeA_561."</td>
       <td>".$row->Confidence_561."</td>
       <td>".$row->SelectB_561."</td>
       <td>".$row->TimeB_561."</td>
       <td>".$row->SelectA_562."</td>
       <td>".$row->TimeA_562."</td>
       <td>".$row->Confidence_562."</td>
       <td>".$row->SelectB_562."</td>
       <td>".$row->TimeB_562."</td>
       <td>".$row->SelectA_563."</td>
       <td>".$row->TimeA_563."</td>
       <td>".$row->Confidence_563."</td>
       <td>".$row->SelectB_563."</td>
       <td>".$row->TimeB_563."</td>
       <td>".$row->SelectA_564."</td>
       <td>".$row->TimeA_564."</td>
       <td>".$row->Confidence_564."</td>
       <td>".$row->SelectB_564."</td>
       <td>".$row->TimeB_564."</td>
       <td>".$row->SelectA_565."</td>
       <td>".$row->TimeA_565."</td>
       <td>".$row->Confidence_565."</td>
       <td>".$row->SelectB_565."</td>
       <td>".$row->TimeB_565."</td>
       <td>".$row->SelectA_566."</td>
       <td>".$row->TimeA_566."</td>
       <td>".$row->Confidence_566."</td>
       <td>".$row->SelectB_566."</td>
       <td>".$row->TimeB_566."</td>
       <td>".$row->SelectA_567."</td>
       <td>".$row->TimeA_567."</td>
       <td>".$row->Confidence_567."</td>
       <td>".$row->SelectB_567."</td>
       <td>".$row->TimeB_567."</td>
       <td>".$row->SelectA_568."</td>
       <td>".$row->TimeA_568."</td>
       <td>".$row->Confidence_568."</td>
       <td>".$row->SelectB_568."</td>
       <td>".$row->TimeB_568."</td>
       <td>".$row->SelectA_569."</td>
       <td>".$row->TimeA_569."</td>
       <td>".$row->Confidence_569."</td>
       <td>".$row->SelectB_569."</td>
       <td>".$row->TimeB_569."</td>
       <td>".$row->SelectA_570."</td>
       <td>".$row->TimeA_570."</td>
       <td>".$row->Confidence_570."</td>
       <td>".$row->SelectB_570."</td>
       <td>".$row->TimeB_570."</td>
       <td>".$row->SelectA_571."</td>
       <td>".$row->TimeA_571."</td>
       <td>".$row->Confidence_571."</td>
       <td>".$row->SelectB_571."</td>
       <td>".$row->TimeB_571."</td>
       <td>".$row->SelectA_572."</td>
       <td>".$row->TimeA_572."</td>
       <td>".$row->Confidence_572."</td>
       <td>".$row->SelectB_572."</td>
       <td>".$row->TimeB_572."</td>
       <td>".$row->SelectA_573."</td>
       <td>".$row->TimeA_573."</td>
       <td>".$row->Confidence_573."</td>
       <td>".$row->SelectB_573."</td>
       <td>".$row->TimeB_573."</td>
       <td>".$row->SelectA_574."</td>
       <td>".$row->TimeA_574."</td>
       <td>".$row->Confidence_574."</td>
       <td>".$row->SelectB_574."</td>
       <td>".$row->TimeB_574."</td>
       <td>".$row->SelectA_575."</td>
       <td>".$row->TimeA_575."</td>
       <td>".$row->Confidence_575."</td>
       <td>".$row->SelectB_575."</td>
       <td>".$row->TimeB_575."</td>
       <td>".$row->SelectA_576."</td>
       <td>".$row->TimeA_576."</td>
       <td>".$row->Confidence_576."</td>
       <td>".$row->SelectB_576."</td>
       <td>".$row->TimeB_576."</td>
       <td>".$row->SelectA_577."</td>
       <td>".$row->TimeA_577."</td>
       <td>".$row->Confidence_577."</td>
       <td>".$row->SelectB_577."</td>
       <td>".$row->TimeB_577."</td>
       <td>".$row->SelectA_578."</td>
       <td>".$row->TimeA_578."</td>
       <td>".$row->Confidence_578."</td>
       <td>".$row->SelectB_578."</td>
       <td>".$row->TimeB_578."</td>
       <td>".$row->SelectA_579."</td>
       <td>".$row->TimeA_579."</td>
       <td>".$row->Confidence_579."</td>
       <td>".$row->SelectB_579."</td>
       <td>".$row->TimeB_579."</td>
       <td>".$row->SelectA_580."</td>
       <td>".$row->TimeA_580."</td>
       <td>".$row->Confidence_580."</td>
       <td>".$row->SelectB_580."</td>
       <td>".$row->TimeB_580."</td>
       <td>".$row->SelectA_581."</td>
       <td>".$row->TimeA_581."</td>
       <td>".$row->Confidence_581."</td>
       <td>".$row->SelectB_581."</td>
       <td>".$row->TimeB_581."</td>
       <td>".$row->SelectA_582."</td>
       <td>".$row->TimeA_582."</td>
       <td>".$row->Confidence_582."</td>
       <td>".$row->SelectB_582."</td>
       <td>".$row->TimeB_582."</td>
       <td>".$row->SelectA_583."</td>
       <td>".$row->TimeA_583."</td>
       <td>".$row->Confidence_583."</td>
       <td>".$row->SelectB_583."</td>
       <td>".$row->TimeB_583."</td>
       <td>".$row->SelectA_584."</td>
       <td>".$row->TimeA_584."</td>
       <td>".$row->Confidence_584."</td>
       <td>".$row->SelectB_584."</td>
       <td>".$row->TimeB_584."</td>
       <td>".$row->SelectA_585."</td>
       <td>".$row->TimeA_585."</td>
       <td>".$row->Confidence_585."</td>
       <td>".$row->SelectB_585."</td>
       <td>".$row->TimeB_585."</td>
       <td>".$row->SelectA_586."</td>
       <td>".$row->TimeA_586."</td>
       <td>".$row->Confidence_586."</td>
       <td>".$row->SelectB_586."</td>
       <td>".$row->TimeB_586."</td>
       <td>".$row->SelectA_587."</td>
       <td>".$row->TimeA_587."</td>
       <td>".$row->Confidence_587."</td>
       <td>".$row->SelectB_587."</td>
       <td>".$row->TimeB_587."</td>
       <td>".$row->SelectA_588."</td>
       <td>".$row->TimeA_588."</td>
       <td>".$row->Confidence_588."</td>
       <td>".$row->SelectB_588."</td>
       <td>".$row->TimeB_588."</td>
       <td>".$row->SelectA_589."</td>
       <td>".$row->TimeA_589."</td>
       <td>".$row->Confidence_589."</td>
       <td>".$row->SelectB_589."</td>
       <td>".$row->TimeB_589."</td>
       <td>".$row->SelectA_590."</td>
       <td>".$row->TimeA_590."</td>
       <td>".$row->Confidence_590."</td>
       <td>".$row->SelectB_590."</td>
       <td>".$row->TimeB_590."</td>
       <td>".$row->SelectA_591."</td>
       <td>".$row->TimeA_591."</td>
       <td>".$row->Confidence_591."</td>
       <td>".$row->SelectB_591."</td>
       <td>".$row->TimeB_591."</td>
       <td>".$row->SelectA_592."</td>
       <td>".$row->TimeA_592."</td>
       <td>".$row->Confidence_592."</td>
       <td>".$row->SelectB_592."</td>
       <td>".$row->TimeB_592."</td>
       <td>".$row->SelectA_593."</td>
       <td>".$row->TimeA_593."</td>
       <td>".$row->Confidence_593."</td>
       <td>".$row->SelectB_593."</td>
       <td>".$row->TimeB_593."</td>
       <td>".$row->SelectA_594."</td>
       <td>".$row->TimeA_594."</td>
       <td>".$row->Confidence_594."</td>
       <td>".$row->SelectB_594."</td>
       <td>".$row->TimeB_594."</td>
       <td>".$row->SelectA_595."</td>
       <td>".$row->TimeA_595."</td>
       <td>".$row->Confidence_595."</td>
       <td>".$row->SelectB_595."</td>
       <td>".$row->TimeB_595."</td>
       <td>".$row->SelectA_596."</td>
       <td>".$row->TimeA_596."</td>
       <td>".$row->Confidence_596."</td>
       <td>".$row->SelectB_596."</td>
       <td>".$row->TimeB_596."</td>
       <td>".$row->SelectA_597."</td>
       <td>".$row->TimeA_597."</td>
       <td>".$row->Confidence_597."</td>
       <td>".$row->SelectB_597."</td>
       <td>".$row->TimeB_597."</td>
       <td>".$row->SelectA_598."</td>
       <td>".$row->TimeA_598."</td>
       <td>".$row->Confidence_598."</td>
       <td>".$row->SelectB_598."</td>
       <td>".$row->TimeB_598."</td>
       <td>".$row->SelectA_599."</td>
       <td>".$row->TimeA_599."</td>
       <td>".$row->Confidence_599."</td>
       <td>".$row->SelectB_599."</td>
       <td>".$row->TimeB_599."</td>
       <td>".$row->SelectA_600."</td>
       <td>".$row->TimeA_600."</td>
       <td>".$row->Confidence_600."</td>
       <td>".$row->SelectB_600."</td>
       <td>".$row->TimeB_600."</td>
       <td>".$row->SelectA_601."</td>
       <td>".$row->TimeA_601."</td>
       <td>".$row->Confidence_601."</td>
       <td>".$row->SelectB_601."</td>
       <td>".$row->TimeB_601."</td>
       <td>".$row->SelectA_602."</td>
       <td>".$row->TimeA_602."</td>
       <td>".$row->Confidence_602."</td>
       <td>".$row->SelectB_602."</td>
       <td>".$row->TimeB_602."</td>
       <td>".$row->SelectA_603."</td>
       <td>".$row->TimeA_603."</td>
       <td>".$row->Confidence_603."</td>
       <td>".$row->SelectB_603."</td>
       <td>".$row->TimeB_603."</td>
       <td>".$row->SelectA_604."</td>
       <td>".$row->TimeA_604."</td>
       <td>".$row->Confidence_604."</td>
       <td>".$row->SelectB_604."</td>
       <td>".$row->TimeB_604."</td>
       <td>".$row->SelectA_605."</td>
       <td>".$row->TimeA_605."</td>
       <td>".$row->Confidence_605."</td>
       <td>".$row->SelectB_605."</td>
       <td>".$row->TimeB_605."</td>
       <td>".$row->SelectA_606."</td>
       <td>".$row->TimeA_606."</td>
       <td>".$row->Confidence_606."</td>
       <td>".$row->SelectB_606."</td>
       <td>".$row->TimeB_606."</td>
       <td>".$row->SelectA_607."</td>
       <td>".$row->TimeA_607."</td>
       <td>".$row->Confidence_607."</td>
       <td>".$row->SelectB_607."</td>
       <td>".$row->TimeB_607."</td>
       <td>".$row->SelectA_608."</td>
       <td>".$row->TimeA_608."</td>
       <td>".$row->Confidence_608."</td>
       <td>".$row->SelectB_608."</td>
       <td>".$row->TimeB_608."</td>
       <td>".$row->SelectA_609."</td>
       <td>".$row->TimeA_609."</td>
       <td>".$row->Confidence_609."</td>
       <td>".$row->SelectB_609."</td>
       <td>".$row->TimeB_609."</td>
       <td>".$row->SelectA_610."</td>
       <td>".$row->TimeA_610."</td>
       <td>".$row->Confidence_610."</td>
       <td>".$row->SelectB_610."</td>
       <td>".$row->TimeB_610."</td>
       <td>".$row->SelectA_611."</td>
       <td>".$row->TimeA_611."</td>
       <td>".$row->Confidence_611."</td>
       <td>".$row->SelectB_611."</td>
       <td>".$row->TimeB_611."</td>
       <td>".$row->SelectA_612."</td>
       <td>".$row->TimeA_612."</td>
       <td>".$row->Confidence_612."</td>
       <td>".$row->SelectB_612."</td>
       <td>".$row->TimeB_612."</td>
       <td>".$row->SelectA_613."</td>
       <td>".$row->TimeA_613."</td>
       <td>".$row->Confidence_613."</td>
       <td>".$row->SelectB_613."</td>
       <td>".$row->TimeB_613."</td>
       <td>".$row->SelectA_614."</td>
       <td>".$row->TimeA_614."</td>
       <td>".$row->Confidence_614."</td>
       <td>".$row->SelectB_614."</td>
       <td>".$row->TimeB_614."</td>
       <td>".$row->SelectA_615."</td>
       <td>".$row->TimeA_615."</td>
       <td>".$row->Confidence_615."</td>
       <td>".$row->SelectB_615."</td>
       <td>".$row->TimeB_615."</td>
       <td>".$row->SelectA_616."</td>
       <td>".$row->TimeA_616."</td>
       <td>".$row->Confidence_616."</td>
       <td>".$row->SelectB_616."</td>
       <td>".$row->TimeB_616."</td>
       <td>".$row->SelectA_617."</td>
       <td>".$row->TimeA_617."</td>
       <td>".$row->Confidence_617."</td>
       <td>".$row->SelectB_617."</td>
       <td>".$row->TimeB_617."</td>
       <td>".$row->SelectA_618."</td>
       <td>".$row->TimeA_618."</td>
       <td>".$row->Confidence_618."</td>
       <td>".$row->SelectB_618."</td>
       <td>".$row->TimeB_618."</td>
       <td>".$row->SelectA_619."</td>
       <td>".$row->TimeA_619."</td>
       <td>".$row->Confidence_619."</td>
       <td>".$row->SelectB_619."</td>
       <td>".$row->TimeB_619."</td>
       <td>".$row->SelectA_620."</td>
       <td>".$row->TimeA_620."</td>
       <td>".$row->Confidence_620."</td>
       <td>".$row->SelectB_620."</td>
       <td>".$row->TimeB_620."</td>
       <td>".$row->SelectA_621."</td>
       <td>".$row->TimeA_621."</td>
       <td>".$row->Confidence_621."</td>
       <td>".$row->SelectB_621."</td>
       <td>".$row->TimeB_621."</td>
       <td>".$row->SelectA_622."</td>
       <td>".$row->TimeA_622."</td>
       <td>".$row->Confidence_622."</td>
       <td>".$row->SelectB_622."</td>
       <td>".$row->TimeB_622."</td>
       <td>".$row->SelectA_623."</td>
       <td>".$row->TimeA_623."</td>
       <td>".$row->Confidence_623."</td>
       <td>".$row->SelectB_623."</td>
       <td>".$row->TimeB_623."</td>
       <td>".$row->SelectA_624."</td>
       <td>".$row->TimeA_624."</td>
       <td>".$row->Confidence_624."</td>
       <td>".$row->SelectB_624."</td>
       <td>".$row->TimeB_624."</td>
       <td>".$row->SelectA_625."</td>
       <td>".$row->TimeA_625."</td>
       <td>".$row->Confidence_625."</td>
       <td>".$row->SelectB_625."</td>
       <td>".$row->TimeB_625."</td>
       <td>".$row->SelectA_626."</td>
       <td>".$row->TimeA_626."</td>
       <td>".$row->Confidence_626."</td>
       <td>".$row->SelectB_626."</td>
       <td>".$row->TimeB_626."</td>
       <td>".$row->SelectA_627."</td>
       <td>".$row->TimeA_627."</td>
       <td>".$row->Confidence_627."</td>
       <td>".$row->SelectB_627."</td>
       <td>".$row->TimeB_627."</td>
       <td>".$row->SelectA_628."</td>
       <td>".$row->TimeA_628."</td>
       <td>".$row->Confidence_628."</td>
       <td>".$row->SelectB_628."</td>
       <td>".$row->TimeB_628."</td>
       <td>".$row->SelectA_629."</td>
       <td>".$row->TimeA_629."</td>
       <td>".$row->Confidence_629."</td>
       <td>".$row->SelectB_629."</td>
       <td>".$row->TimeB_629."</td>
       <td>".$row->SelectA_630."</td>
       <td>".$row->TimeA_630."</td>
       <td>".$row->Confidence_630."</td>
       <td>".$row->SelectB_630."</td>
       <td>".$row->TimeB_630."</td>
       <td>".$row->SelectA_631."</td>
       <td>".$row->TimeA_631."</td>
       <td>".$row->Confidence_631."</td>
       <td>".$row->SelectB_631."</td>
       <td>".$row->TimeB_631."</td>
       <td>".$row->SelectA_632."</td>
       <td>".$row->TimeA_632."</td>
       <td>".$row->Confidence_632."</td>
       <td>".$row->SelectB_632."</td>
       <td>".$row->TimeB_632."</td>
       <td>".$row->SelectA_633."</td>
       <td>".$row->TimeA_633."</td>
       <td>".$row->Confidence_633."</td>
       <td>".$row->SelectB_633."</td>
       <td>".$row->TimeB_633."</td>
       <td>".$row->SelectA_634."</td>
       <td>".$row->TimeA_634."</td>
       <td>".$row->Confidence_634."</td>
       <td>".$row->SelectB_634."</td>
       <td>".$row->TimeB_634."</td>
       <td>".$row->SelectA_635."</td>
       <td>".$row->TimeA_635."</td>
       <td>".$row->Confidence_635."</td>
       <td>".$row->SelectB_635."</td>
       <td>".$row->TimeB_635."</td>
       <td>".$row->SelectA_636."</td>
       <td>".$row->TimeA_636."</td>
       <td>".$row->Confidence_636."</td>
       <td>".$row->SelectB_636."</td>
       <td>".$row->TimeB_636."</td>
       <td>".$row->SelectA_637."</td>
       <td>".$row->TimeA_637."</td>
       <td>".$row->Confidence_637."</td>
       <td>".$row->SelectB_637."</td>
       <td>".$row->TimeB_637."</td>
       <td>".$row->SelectA_638."</td>
       <td>".$row->TimeA_638."</td>
       <td>".$row->Confidence_638."</td>
       <td>".$row->SelectB_638."</td>
       <td>".$row->TimeB_638."</td>
       <td>".$row->SelectA_639."</td>
       <td>".$row->TimeA_639."</td>
       <td>".$row->Confidence_639."</td>
       <td>".$row->SelectB_639."</td>
       <td>".$row->TimeB_639."</td>
       <td>".$row->SelectA_640."</td>
       <td>".$row->TimeA_640."</td>
       <td>".$row->Confidence_640."</td>
       <td>".$row->SelectB_640."</td>
       <td>".$row->TimeB_640."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";

echo $EXCEL_FILE;

?>
