<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=481; $k<561; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 481; $ii < 561; $ii++){
    $qry .= "a2.SelectA_".$ii.", a2.TimeA_".$ii.", a2.Confidence_".$ii.", b2.SelectB_".$ii.", b2.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_7 as a2, Data_B_7 as b2 where u.uid = a2.uid and u.uid = b2.uid";
$res = $mysqli->query($qry);

//echo $qry;

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_481."</td>
       <td>".$row->TimeA_481."</td>
       <td>".$row->Confidence_481."</td>
       <td>".$row->SelectB_481."</td>
       <td>".$row->TimeB_481."</td>
       <td>".$row->SelectA_482."</td>
       <td>".$row->TimeA_482."</td>
       <td>".$row->Confidence_482."</td>
       <td>".$row->SelectB_482."</td>
       <td>".$row->TimeB_482."</td>
       <td>".$row->SelectA_483."</td>
       <td>".$row->TimeA_483."</td>
       <td>".$row->Confidence_483."</td>
       <td>".$row->SelectB_483."</td>
       <td>".$row->TimeB_483."</td>
       <td>".$row->SelectA_484."</td>
       <td>".$row->TimeA_484."</td>
       <td>".$row->Confidence_484."</td>
       <td>".$row->SelectB_484."</td>
       <td>".$row->TimeB_484."</td>
       <td>".$row->SelectA_485."</td>
       <td>".$row->TimeA_485."</td>
       <td>".$row->Confidence_485."</td>
       <td>".$row->SelectB_485."</td>
       <td>".$row->TimeB_485."</td>
       <td>".$row->SelectA_486."</td>
       <td>".$row->TimeA_486."</td>
       <td>".$row->Confidence_486."</td>
       <td>".$row->SelectB_486."</td>
       <td>".$row->TimeB_486."</td>
       <td>".$row->SelectA_487."</td>
       <td>".$row->TimeA_487."</td>
       <td>".$row->Confidence_487."</td>
       <td>".$row->SelectB_487."</td>
       <td>".$row->TimeB_487."</td>
       <td>".$row->SelectA_488."</td>
       <td>".$row->TimeA_488."</td>
       <td>".$row->Confidence_488."</td>
       <td>".$row->SelectB_488."</td>
       <td>".$row->TimeB_488."</td>
       <td>".$row->SelectA_489."</td>
       <td>".$row->TimeA_489."</td>
       <td>".$row->Confidence_489."</td>
       <td>".$row->SelectB_489."</td>
       <td>".$row->TimeB_489."</td>
       <td>".$row->SelectA_490."</td>
       <td>".$row->TimeA_490."</td>
       <td>".$row->Confidence_490."</td>
       <td>".$row->SelectB_490."</td>
       <td>".$row->TimeB_490."</td>
       <td>".$row->SelectA_491."</td>
       <td>".$row->TimeA_491."</td>
       <td>".$row->Confidence_491."</td>
       <td>".$row->SelectB_491."</td>
       <td>".$row->TimeB_491."</td>
       <td>".$row->SelectA_492."</td>
       <td>".$row->TimeA_492."</td>
       <td>".$row->Confidence_492."</td>
       <td>".$row->SelectB_492."</td>
       <td>".$row->TimeB_492."</td>
       <td>".$row->SelectA_493."</td>
       <td>".$row->TimeA_493."</td>
       <td>".$row->Confidence_493."</td>
       <td>".$row->SelectB_493."</td>
       <td>".$row->TimeB_493."</td>
       <td>".$row->SelectA_494."</td>
       <td>".$row->TimeA_494."</td>
       <td>".$row->Confidence_494."</td>
       <td>".$row->SelectB_494."</td>
       <td>".$row->TimeB_494."</td>
       <td>".$row->SelectA_495."</td>
       <td>".$row->TimeA_495."</td>
       <td>".$row->Confidence_495."</td>
       <td>".$row->SelectB_495."</td>
       <td>".$row->TimeB_495."</td>
       <td>".$row->SelectA_496."</td>
       <td>".$row->TimeA_496."</td>
       <td>".$row->Confidence_496."</td>
       <td>".$row->SelectB_496."</td>
       <td>".$row->TimeB_496."</td>
       <td>".$row->SelectA_497."</td>
       <td>".$row->TimeA_497."</td>
       <td>".$row->Confidence_497."</td>
       <td>".$row->SelectB_497."</td>
       <td>".$row->TimeB_497."</td>
       <td>".$row->SelectA_498."</td>
       <td>".$row->TimeA_498."</td>
       <td>".$row->Confidence_498."</td>
       <td>".$row->SelectB_498."</td>
       <td>".$row->TimeB_498."</td>
       <td>".$row->SelectA_499."</td>
       <td>".$row->TimeA_499."</td>
       <td>".$row->Confidence_499."</td>
       <td>".$row->SelectB_499."</td>
       <td>".$row->TimeB_499."</td>
       <td>".$row->SelectA_500."</td>
       <td>".$row->TimeA_500."</td>
       <td>".$row->Confidence_500."</td>
       <td>".$row->SelectB_500."</td>
       <td>".$row->TimeB_500."</td>
       <td>".$row->SelectA_501."</td>
       <td>".$row->TimeA_501."</td>
       <td>".$row->Confidence_501."</td>
       <td>".$row->SelectB_501."</td>
       <td>".$row->TimeB_501."</td>
       <td>".$row->SelectA_502."</td>
       <td>".$row->TimeA_502."</td>
       <td>".$row->Confidence_502."</td>
       <td>".$row->SelectB_502."</td>
       <td>".$row->TimeB_502."</td>
       <td>".$row->SelectA_503."</td>
       <td>".$row->TimeA_503."</td>
       <td>".$row->Confidence_503."</td>
       <td>".$row->SelectB_503."</td>
       <td>".$row->TimeB_503."</td>
       <td>".$row->SelectA_504."</td>
       <td>".$row->TimeA_504."</td>
       <td>".$row->Confidence_504."</td>
       <td>".$row->SelectB_504."</td>
       <td>".$row->TimeB_504."</td>
       <td>".$row->SelectA_505."</td>
       <td>".$row->TimeA_505."</td>
       <td>".$row->Confidence_505."</td>
       <td>".$row->SelectB_505."</td>
       <td>".$row->TimeB_505."</td>
       <td>".$row->SelectA_506."</td>
       <td>".$row->TimeA_506."</td>
       <td>".$row->Confidence_506."</td>
       <td>".$row->SelectB_506."</td>
       <td>".$row->TimeB_506."</td>
       <td>".$row->SelectA_507."</td>
       <td>".$row->TimeA_507."</td>
       <td>".$row->Confidence_507."</td>
       <td>".$row->SelectB_507."</td>
       <td>".$row->TimeB_507."</td>
       <td>".$row->SelectA_508."</td>
       <td>".$row->TimeA_508."</td>
       <td>".$row->Confidence_508."</td>
       <td>".$row->SelectB_508."</td>
       <td>".$row->TimeB_508."</td>
       <td>".$row->SelectA_509."</td>
       <td>".$row->TimeA_509."</td>
       <td>".$row->Confidence_509."</td>
       <td>".$row->SelectB_509."</td>
       <td>".$row->TimeB_509."</td>
       <td>".$row->SelectA_510."</td>
       <td>".$row->TimeA_510."</td>
       <td>".$row->Confidence_510."</td>
       <td>".$row->SelectB_510."</td>
       <td>".$row->TimeB_510."</td>
       <td>".$row->SelectA_511."</td>
       <td>".$row->TimeA_511."</td>
       <td>".$row->Confidence_511."</td>
       <td>".$row->SelectB_511."</td>
       <td>".$row->TimeB_511."</td>
       <td>".$row->SelectA_512."</td>
       <td>".$row->TimeA_512."</td>
       <td>".$row->Confidence_512."</td>
       <td>".$row->SelectB_512."</td>
       <td>".$row->TimeB_512."</td>
       <td>".$row->SelectA_513."</td>
       <td>".$row->TimeA_513."</td>
       <td>".$row->Confidence_513."</td>
       <td>".$row->SelectB_513."</td>
       <td>".$row->TimeB_513."</td>
       <td>".$row->SelectA_514."</td>
       <td>".$row->TimeA_514."</td>
       <td>".$row->Confidence_514."</td>
       <td>".$row->SelectB_514."</td>
       <td>".$row->TimeB_514."</td>
       <td>".$row->SelectA_515."</td>
       <td>".$row->TimeA_515."</td>
       <td>".$row->Confidence_515."</td>
       <td>".$row->SelectB_515."</td>
       <td>".$row->TimeB_515."</td>
       <td>".$row->SelectA_516."</td>
       <td>".$row->TimeA_516."</td>
       <td>".$row->Confidence_516."</td>
       <td>".$row->SelectB_516."</td>
       <td>".$row->TimeB_516."</td>
       <td>".$row->SelectA_517."</td>
       <td>".$row->TimeA_517."</td>
       <td>".$row->Confidence_517."</td>
       <td>".$row->SelectB_517."</td>
       <td>".$row->TimeB_517."</td>
       <td>".$row->SelectA_518."</td>
       <td>".$row->TimeA_518."</td>
       <td>".$row->Confidence_518."</td>
       <td>".$row->SelectB_518."</td>
       <td>".$row->TimeB_518."</td>
       <td>".$row->SelectA_519."</td>
       <td>".$row->TimeA_519."</td>
       <td>".$row->Confidence_519."</td>
       <td>".$row->SelectB_519."</td>
       <td>".$row->TimeB_519."</td>
       <td>".$row->SelectA_520."</td>
       <td>".$row->TimeA_520."</td>
       <td>".$row->Confidence_520."</td>
       <td>".$row->SelectB_520."</td>
       <td>".$row->TimeB_520."</td>
       <td>".$row->SelectA_521."</td>
       <td>".$row->TimeA_521."</td>
       <td>".$row->Confidence_521."</td>
       <td>".$row->SelectB_521."</td>
       <td>".$row->TimeB_521."</td>
       <td>".$row->SelectA_522."</td>
       <td>".$row->TimeA_522."</td>
       <td>".$row->Confidence_522."</td>
       <td>".$row->SelectB_522."</td>
       <td>".$row->TimeB_522."</td>
       <td>".$row->SelectA_523."</td>
       <td>".$row->TimeA_523."</td>
       <td>".$row->Confidence_523."</td>
       <td>".$row->SelectB_523."</td>
       <td>".$row->TimeB_523."</td>
       <td>".$row->SelectA_524."</td>
       <td>".$row->TimeA_524."</td>
       <td>".$row->Confidence_524."</td>
       <td>".$row->SelectB_524."</td>
       <td>".$row->TimeB_524."</td>
       <td>".$row->SelectA_525."</td>
       <td>".$row->TimeA_525."</td>
       <td>".$row->Confidence_525."</td>
       <td>".$row->SelectB_525."</td>
       <td>".$row->TimeB_525."</td>
       <td>".$row->SelectA_526."</td>
       <td>".$row->TimeA_526."</td>
       <td>".$row->Confidence_526."</td>
       <td>".$row->SelectB_526."</td>
       <td>".$row->TimeB_526."</td>
       <td>".$row->SelectA_527."</td>
       <td>".$row->TimeA_527."</td>
       <td>".$row->Confidence_527."</td>
       <td>".$row->SelectB_527."</td>
       <td>".$row->TimeB_527."</td>
       <td>".$row->SelectA_528."</td>
       <td>".$row->TimeA_528."</td>
       <td>".$row->Confidence_528."</td>
       <td>".$row->SelectB_528."</td>
       <td>".$row->TimeB_528."</td>
       <td>".$row->SelectA_529."</td>
       <td>".$row->TimeA_529."</td>
       <td>".$row->Confidence_529."</td>
       <td>".$row->SelectB_529."</td>
       <td>".$row->TimeB_529."</td>
       <td>".$row->SelectA_530."</td>
       <td>".$row->TimeA_530."</td>
       <td>".$row->Confidence_530."</td>
       <td>".$row->SelectB_530."</td>
       <td>".$row->TimeB_530."</td>
       <td>".$row->SelectA_531."</td>
       <td>".$row->TimeA_531."</td>
       <td>".$row->Confidence_531."</td>
       <td>".$row->SelectB_531."</td>
       <td>".$row->TimeB_531."</td>
       <td>".$row->SelectA_532."</td>
       <td>".$row->TimeA_532."</td>
       <td>".$row->Confidence_532."</td>
       <td>".$row->SelectB_532."</td>
       <td>".$row->TimeB_532."</td>
       <td>".$row->SelectA_533."</td>
       <td>".$row->TimeA_533."</td>
       <td>".$row->Confidence_533."</td>
       <td>".$row->SelectB_533."</td>
       <td>".$row->TimeB_533."</td>
       <td>".$row->SelectA_534."</td>
       <td>".$row->TimeA_534."</td>
       <td>".$row->Confidence_534."</td>
       <td>".$row->SelectB_534."</td>
       <td>".$row->TimeB_534."</td>
       <td>".$row->SelectA_535."</td>
       <td>".$row->TimeA_535."</td>
       <td>".$row->Confidence_535."</td>
       <td>".$row->SelectB_535."</td>
       <td>".$row->TimeB_535."</td>
       <td>".$row->SelectA_536."</td>
       <td>".$row->TimeA_536."</td>
       <td>".$row->Confidence_536."</td>
       <td>".$row->SelectB_536."</td>
       <td>".$row->TimeB_536."</td>
       <td>".$row->SelectA_537."</td>
       <td>".$row->TimeA_537."</td>
       <td>".$row->Confidence_537."</td>
       <td>".$row->SelectB_537."</td>
       <td>".$row->TimeB_537."</td>
       <td>".$row->SelectA_538."</td>
       <td>".$row->TimeA_538."</td>
       <td>".$row->Confidence_538."</td>
       <td>".$row->SelectB_538."</td>
       <td>".$row->TimeB_538."</td>
       <td>".$row->SelectA_539."</td>
       <td>".$row->TimeA_539."</td>
       <td>".$row->Confidence_539."</td>
       <td>".$row->SelectB_539."</td>
       <td>".$row->TimeB_539."</td>
       <td>".$row->SelectA_540."</td>
       <td>".$row->TimeA_540."</td>
       <td>".$row->Confidence_540."</td>
       <td>".$row->SelectB_540."</td>
       <td>".$row->TimeB_540."</td>
       <td>".$row->SelectA_541."</td>
       <td>".$row->TimeA_541."</td>
       <td>".$row->Confidence_541."</td>
       <td>".$row->SelectB_541."</td>
       <td>".$row->TimeB_541."</td>
       <td>".$row->SelectA_542."</td>
       <td>".$row->TimeA_542."</td>
       <td>".$row->Confidence_542."</td>
       <td>".$row->SelectB_542."</td>
       <td>".$row->TimeB_542."</td>
       <td>".$row->SelectA_543."</td>
       <td>".$row->TimeA_543."</td>
       <td>".$row->Confidence_543."</td>
       <td>".$row->SelectB_543."</td>
       <td>".$row->TimeB_543."</td>
       <td>".$row->SelectA_544."</td>
       <td>".$row->TimeA_544."</td>
       <td>".$row->Confidence_544."</td>
       <td>".$row->SelectB_544."</td>
       <td>".$row->TimeB_544."</td>
       <td>".$row->SelectA_545."</td>
       <td>".$row->TimeA_545."</td>
       <td>".$row->Confidence_545."</td>
       <td>".$row->SelectB_545."</td>
       <td>".$row->TimeB_545."</td>
       <td>".$row->SelectA_546."</td>
       <td>".$row->TimeA_546."</td>
       <td>".$row->Confidence_546."</td>
       <td>".$row->SelectB_546."</td>
       <td>".$row->TimeB_546."</td>
       <td>".$row->SelectA_547."</td>
       <td>".$row->TimeA_547."</td>
       <td>".$row->Confidence_547."</td>
       <td>".$row->SelectB_547."</td>
       <td>".$row->TimeB_547."</td>
       <td>".$row->SelectA_548."</td>
       <td>".$row->TimeA_548."</td>
       <td>".$row->Confidence_548."</td>
       <td>".$row->SelectB_548."</td>
       <td>".$row->TimeB_548."</td>
       <td>".$row->SelectA_549."</td>
       <td>".$row->TimeA_549."</td>
       <td>".$row->Confidence_549."</td>
       <td>".$row->SelectB_549."</td>
       <td>".$row->TimeB_549."</td>
       <td>".$row->SelectA_550."</td>
       <td>".$row->TimeA_550."</td>
       <td>".$row->Confidence_550."</td>
       <td>".$row->SelectB_550."</td>
       <td>".$row->TimeB_550."</td>
       <td>".$row->SelectA_551."</td>
       <td>".$row->TimeA_551."</td>
       <td>".$row->Confidence_551."</td>
       <td>".$row->SelectB_551."</td>
       <td>".$row->TimeB_551."</td>
       <td>".$row->SelectA_552."</td>
       <td>".$row->TimeA_552."</td>
       <td>".$row->Confidence_552."</td>
       <td>".$row->SelectB_552."</td>
       <td>".$row->TimeB_552."</td>
       <td>".$row->SelectA_553."</td>
       <td>".$row->TimeA_553."</td>
       <td>".$row->Confidence_553."</td>
       <td>".$row->SelectB_553."</td>
       <td>".$row->TimeB_553."</td>
       <td>".$row->SelectA_554."</td>
       <td>".$row->TimeA_554."</td>
       <td>".$row->Confidence_554."</td>
       <td>".$row->SelectB_554."</td>
       <td>".$row->TimeB_554."</td>
       <td>".$row->SelectA_555."</td>
       <td>".$row->TimeA_555."</td>
       <td>".$row->Confidence_555."</td>
       <td>".$row->SelectB_555."</td>
       <td>".$row->TimeB_555."</td>
       <td>".$row->SelectA_556."</td>
       <td>".$row->TimeA_556."</td>
       <td>".$row->Confidence_556."</td>
       <td>".$row->SelectB_556."</td>
       <td>".$row->TimeB_556."</td>
       <td>".$row->SelectA_557."</td>
       <td>".$row->TimeA_557."</td>
       <td>".$row->Confidence_557."</td>
       <td>".$row->SelectB_557."</td>
       <td>".$row->TimeB_557."</td>
       <td>".$row->SelectA_558."</td>
       <td>".$row->TimeA_558."</td>
       <td>".$row->Confidence_558."</td>
       <td>".$row->SelectB_558."</td>
       <td>".$row->TimeB_558."</td>
       <td>".$row->SelectA_559."</td>
       <td>".$row->TimeA_559."</td>
       <td>".$row->Confidence_559."</td>
       <td>".$row->SelectB_559."</td>
       <td>".$row->TimeB_559."</td>
       <td>".$row->SelectA_560."</td>
       <td>".$row->TimeA_560."</td>
       <td>".$row->Confidence_560."</td>
       <td>".$row->SelectB_560."</td>
       <td>".$row->TimeB_560."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";

echo $EXCEL_FILE;

?>
