<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=321; $k<401; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 321; $ii < 401; $ii++){
    $qry .= "a2.SelectA_".$ii.", a2.TimeA_".$ii.", a2.Confidence_".$ii.", b2.SelectB_".$ii.", b2.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_5 as a2, Data_B_5 as b2 where u.uid = a2.uid and u.uid = b2.uid";
$res = $mysqli->query($qry);

//echo $qry;

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_321."</td>
       <td>".$row->TimeA_321."</td>
       <td>".$row->Confidence_321."</td>
       <td>".$row->SelectB_321."</td>
       <td>".$row->TimeB_321."</td>
       <td>".$row->SelectA_322."</td>
       <td>".$row->TimeA_322."</td>
       <td>".$row->Confidence_322."</td>
       <td>".$row->SelectB_322."</td>
       <td>".$row->TimeB_322."</td>
       <td>".$row->SelectA_323."</td>
       <td>".$row->TimeA_323."</td>
       <td>".$row->Confidence_323."</td>
       <td>".$row->SelectB_323."</td>
       <td>".$row->TimeB_323."</td>
       <td>".$row->SelectA_324."</td>
       <td>".$row->TimeA_324."</td>
       <td>".$row->Confidence_324."</td>
       <td>".$row->SelectB_324."</td>
       <td>".$row->TimeB_324."</td>
       <td>".$row->SelectA_325."</td>
       <td>".$row->TimeA_325."</td>
       <td>".$row->Confidence_325."</td>
       <td>".$row->SelectB_325."</td>
       <td>".$row->TimeB_325."</td>
       <td>".$row->SelectA_326."</td>
       <td>".$row->TimeA_326."</td>
       <td>".$row->Confidence_326."</td>
       <td>".$row->SelectB_326."</td>
       <td>".$row->TimeB_326."</td>
       <td>".$row->SelectA_327."</td>
       <td>".$row->TimeA_327."</td>
       <td>".$row->Confidence_327."</td>
       <td>".$row->SelectB_327."</td>
       <td>".$row->TimeB_327."</td>
       <td>".$row->SelectA_328."</td>
       <td>".$row->TimeA_328."</td>
       <td>".$row->Confidence_328."</td>
       <td>".$row->SelectB_328."</td>
       <td>".$row->TimeB_328."</td>
       <td>".$row->SelectA_329."</td>
       <td>".$row->TimeA_329."</td>
       <td>".$row->Confidence_329."</td>
       <td>".$row->SelectB_329."</td>
       <td>".$row->TimeB_329."</td>
       <td>".$row->SelectA_330."</td>
       <td>".$row->TimeA_330."</td>
       <td>".$row->Confidence_330."</td>
       <td>".$row->SelectB_330."</td>
       <td>".$row->TimeB_330."</td>
       <td>".$row->SelectA_331."</td>
       <td>".$row->TimeA_331."</td>
       <td>".$row->Confidence_331."</td>
       <td>".$row->SelectB_331."</td>
       <td>".$row->TimeB_331."</td>
       <td>".$row->SelectA_332."</td>
       <td>".$row->TimeA_332."</td>
       <td>".$row->Confidence_332."</td>
       <td>".$row->SelectB_332."</td>
       <td>".$row->TimeB_332."</td>
       <td>".$row->SelectA_333."</td>
       <td>".$row->TimeA_333."</td>
       <td>".$row->Confidence_333."</td>
       <td>".$row->SelectB_333."</td>
       <td>".$row->TimeB_333."</td>
       <td>".$row->SelectA_334."</td>
       <td>".$row->TimeA_334."</td>
       <td>".$row->Confidence_334."</td>
       <td>".$row->SelectB_334."</td>
       <td>".$row->TimeB_334."</td>
       <td>".$row->SelectA_335."</td>
       <td>".$row->TimeA_335."</td>
       <td>".$row->Confidence_335."</td>
       <td>".$row->SelectB_335."</td>
       <td>".$row->TimeB_335."</td>
       <td>".$row->SelectA_336."</td>
       <td>".$row->TimeA_336."</td>
       <td>".$row->Confidence_336."</td>
       <td>".$row->SelectB_336."</td>
       <td>".$row->TimeB_336."</td>
       <td>".$row->SelectA_337."</td>
       <td>".$row->TimeA_337."</td>
       <td>".$row->Confidence_337."</td>
       <td>".$row->SelectB_337."</td>
       <td>".$row->TimeB_337."</td>
       <td>".$row->SelectA_338."</td>
       <td>".$row->TimeA_338."</td>
       <td>".$row->Confidence_338."</td>
       <td>".$row->SelectB_338."</td>
       <td>".$row->TimeB_338."</td>
       <td>".$row->SelectA_339."</td>
       <td>".$row->TimeA_339."</td>
       <td>".$row->Confidence_339."</td>
       <td>".$row->SelectB_339."</td>
       <td>".$row->TimeB_339."</td>
       <td>".$row->SelectA_340."</td>
       <td>".$row->TimeA_340."</td>
       <td>".$row->Confidence_340."</td>
       <td>".$row->SelectB_340."</td>
       <td>".$row->TimeB_340."</td>
       <td>".$row->SelectA_341."</td>
       <td>".$row->TimeA_341."</td>
       <td>".$row->Confidence_341."</td>
       <td>".$row->SelectB_341."</td>
       <td>".$row->TimeB_341."</td>
       <td>".$row->SelectA_342."</td>
       <td>".$row->TimeA_342."</td>
       <td>".$row->Confidence_342."</td>
       <td>".$row->SelectB_342."</td>
       <td>".$row->TimeB_342."</td>
       <td>".$row->SelectA_343."</td>
       <td>".$row->TimeA_343."</td>
       <td>".$row->Confidence_343."</td>
       <td>".$row->SelectB_343."</td>
       <td>".$row->TimeB_343."</td>
       <td>".$row->SelectA_344."</td>
       <td>".$row->TimeA_344."</td>
       <td>".$row->Confidence_344."</td>
       <td>".$row->SelectB_344."</td>
       <td>".$row->TimeB_344."</td>
       <td>".$row->SelectA_345."</td>
       <td>".$row->TimeA_345."</td>
       <td>".$row->Confidence_345."</td>
       <td>".$row->SelectB_345."</td>
       <td>".$row->TimeB_345."</td>
       <td>".$row->SelectA_346."</td>
       <td>".$row->TimeA_346."</td>
       <td>".$row->Confidence_346."</td>
       <td>".$row->SelectB_346."</td>
       <td>".$row->TimeB_346."</td>
       <td>".$row->SelectA_347."</td>
       <td>".$row->TimeA_347."</td>
       <td>".$row->Confidence_347."</td>
       <td>".$row->SelectB_347."</td>
       <td>".$row->TimeB_347."</td>
       <td>".$row->SelectA_348."</td>
       <td>".$row->TimeA_348."</td>
       <td>".$row->Confidence_348."</td>
       <td>".$row->SelectB_348."</td>
       <td>".$row->TimeB_348."</td>
       <td>".$row->SelectA_349."</td>
       <td>".$row->TimeA_349."</td>
       <td>".$row->Confidence_349."</td>
       <td>".$row->SelectB_349."</td>
       <td>".$row->TimeB_349."</td>
       <td>".$row->SelectA_350."</td>
       <td>".$row->TimeA_350."</td>
       <td>".$row->Confidence_350."</td>
       <td>".$row->SelectB_350."</td>
       <td>".$row->TimeB_350."</td>
       <td>".$row->SelectA_351."</td>
       <td>".$row->TimeA_351."</td>
       <td>".$row->Confidence_351."</td>
       <td>".$row->SelectB_351."</td>
       <td>".$row->TimeB_351."</td>
       <td>".$row->SelectA_352."</td>
       <td>".$row->TimeA_352."</td>
       <td>".$row->Confidence_352."</td>
       <td>".$row->SelectB_352."</td>
       <td>".$row->TimeB_352."</td>
       <td>".$row->SelectA_353."</td>
       <td>".$row->TimeA_353."</td>
       <td>".$row->Confidence_353."</td>
       <td>".$row->SelectB_353."</td>
       <td>".$row->TimeB_353."</td>
       <td>".$row->SelectA_354."</td>
       <td>".$row->TimeA_354."</td>
       <td>".$row->Confidence_354."</td>
       <td>".$row->SelectB_354."</td>
       <td>".$row->TimeB_354."</td>
       <td>".$row->SelectA_355."</td>
       <td>".$row->TimeA_355."</td>
       <td>".$row->Confidence_355."</td>
       <td>".$row->SelectB_355."</td>
       <td>".$row->TimeB_355."</td>
       <td>".$row->SelectA_356."</td>
       <td>".$row->TimeA_356."</td>
       <td>".$row->Confidence_356."</td>
       <td>".$row->SelectB_356."</td>
       <td>".$row->TimeB_356."</td>
       <td>".$row->SelectA_357."</td>
       <td>".$row->TimeA_357."</td>
       <td>".$row->Confidence_357."</td>
       <td>".$row->SelectB_357."</td>
       <td>".$row->TimeB_357."</td>
       <td>".$row->SelectA_358."</td>
       <td>".$row->TimeA_358."</td>
       <td>".$row->Confidence_358."</td>
       <td>".$row->SelectB_358."</td>
       <td>".$row->TimeB_358."</td>
       <td>".$row->SelectA_359."</td>
       <td>".$row->TimeA_359."</td>
       <td>".$row->Confidence_359."</td>
       <td>".$row->SelectB_359."</td>
       <td>".$row->TimeB_359."</td>
       <td>".$row->SelectA_360."</td>
       <td>".$row->TimeA_360."</td>
       <td>".$row->Confidence_360."</td>
       <td>".$row->SelectB_360."</td>
       <td>".$row->TimeB_360."</td>
       <td>".$row->SelectA_361."</td>
       <td>".$row->TimeA_361."</td>
       <td>".$row->Confidence_361."</td>
       <td>".$row->SelectB_361."</td>
       <td>".$row->TimeB_361."</td>
       <td>".$row->SelectA_362."</td>
       <td>".$row->TimeA_362."</td>
       <td>".$row->Confidence_362."</td>
       <td>".$row->SelectB_362."</td>
       <td>".$row->TimeB_362."</td>
       <td>".$row->SelectA_363."</td>
       <td>".$row->TimeA_363."</td>
       <td>".$row->Confidence_363."</td>
       <td>".$row->SelectB_363."</td>
       <td>".$row->TimeB_363."</td>
       <td>".$row->SelectA_364."</td>
       <td>".$row->TimeA_364."</td>
       <td>".$row->Confidence_364."</td>
       <td>".$row->SelectB_364."</td>
       <td>".$row->TimeB_364."</td>
       <td>".$row->SelectA_365."</td>
       <td>".$row->TimeA_365."</td>
       <td>".$row->Confidence_365."</td>
       <td>".$row->SelectB_365."</td>
       <td>".$row->TimeB_365."</td>
       <td>".$row->SelectA_366."</td>
       <td>".$row->TimeA_366."</td>
       <td>".$row->Confidence_366."</td>
       <td>".$row->SelectB_366."</td>
       <td>".$row->TimeB_366."</td>
       <td>".$row->SelectA_367."</td>
       <td>".$row->TimeA_367."</td>
       <td>".$row->Confidence_367."</td>
       <td>".$row->SelectB_367."</td>
       <td>".$row->TimeB_367."</td>
       <td>".$row->SelectA_368."</td>
       <td>".$row->TimeA_368."</td>
       <td>".$row->Confidence_368."</td>
       <td>".$row->SelectB_368."</td>
       <td>".$row->TimeB_368."</td>
       <td>".$row->SelectA_369."</td>
       <td>".$row->TimeA_369."</td>
       <td>".$row->Confidence_369."</td>
       <td>".$row->SelectB_369."</td>
       <td>".$row->TimeB_369."</td>
       <td>".$row->SelectA_370."</td>
       <td>".$row->TimeA_370."</td>
       <td>".$row->Confidence_370."</td>
       <td>".$row->SelectB_370."</td>
       <td>".$row->TimeB_370."</td>
       <td>".$row->SelectA_371."</td>
       <td>".$row->TimeA_371."</td>
       <td>".$row->Confidence_371."</td>
       <td>".$row->SelectB_371."</td>
       <td>".$row->TimeB_371."</td>
       <td>".$row->SelectA_372."</td>
       <td>".$row->TimeA_372."</td>
       <td>".$row->Confidence_372."</td>
       <td>".$row->SelectB_372."</td>
       <td>".$row->TimeB_372."</td>
       <td>".$row->SelectA_373."</td>
       <td>".$row->TimeA_373."</td>
       <td>".$row->Confidence_373."</td>
       <td>".$row->SelectB_373."</td>
       <td>".$row->TimeB_373."</td>
       <td>".$row->SelectA_374."</td>
       <td>".$row->TimeA_374."</td>
       <td>".$row->Confidence_374."</td>
       <td>".$row->SelectB_374."</td>
       <td>".$row->TimeB_374."</td>
       <td>".$row->SelectA_375."</td>
       <td>".$row->TimeA_375."</td>
       <td>".$row->Confidence_375."</td>
       <td>".$row->SelectB_375."</td>
       <td>".$row->TimeB_375."</td>
       <td>".$row->SelectA_376."</td>
       <td>".$row->TimeA_376."</td>
       <td>".$row->Confidence_376."</td>
       <td>".$row->SelectB_376."</td>
       <td>".$row->TimeB_376."</td>
       <td>".$row->SelectA_377."</td>
       <td>".$row->TimeA_377."</td>
       <td>".$row->Confidence_377."</td>
       <td>".$row->SelectB_377."</td>
       <td>".$row->TimeB_377."</td>
       <td>".$row->SelectA_378."</td>
       <td>".$row->TimeA_378."</td>
       <td>".$row->Confidence_378."</td>
       <td>".$row->SelectB_378."</td>
       <td>".$row->TimeB_378."</td>
       <td>".$row->SelectA_379."</td>
       <td>".$row->TimeA_379."</td>
       <td>".$row->Confidence_379."</td>
       <td>".$row->SelectB_379."</td>
       <td>".$row->TimeB_379."</td>
       <td>".$row->SelectA_380."</td>
       <td>".$row->TimeA_380."</td>
       <td>".$row->Confidence_380."</td>
       <td>".$row->SelectB_380."</td>
       <td>".$row->TimeB_380."</td>
       <td>".$row->SelectA_381."</td>
       <td>".$row->TimeA_381."</td>
       <td>".$row->Confidence_381."</td>
       <td>".$row->SelectB_381."</td>
       <td>".$row->TimeB_381."</td>
       <td>".$row->SelectA_382."</td>
       <td>".$row->TimeA_382."</td>
       <td>".$row->Confidence_382."</td>
       <td>".$row->SelectB_382."</td>
       <td>".$row->TimeB_382."</td>
       <td>".$row->SelectA_383."</td>
       <td>".$row->TimeA_383."</td>
       <td>".$row->Confidence_383."</td>
       <td>".$row->SelectB_383."</td>
       <td>".$row->TimeB_383."</td>
       <td>".$row->SelectA_384."</td>
       <td>".$row->TimeA_384."</td>
       <td>".$row->Confidence_384."</td>
       <td>".$row->SelectB_384."</td>
       <td>".$row->TimeB_384."</td>
       <td>".$row->SelectA_385."</td>
       <td>".$row->TimeA_385."</td>
       <td>".$row->Confidence_385."</td>
       <td>".$row->SelectB_385."</td>
       <td>".$row->TimeB_385."</td>
       <td>".$row->SelectA_386."</td>
       <td>".$row->TimeA_386."</td>
       <td>".$row->Confidence_386."</td>
       <td>".$row->SelectB_386."</td>
       <td>".$row->TimeB_386."</td>
       <td>".$row->SelectA_387."</td>
       <td>".$row->TimeA_387."</td>
       <td>".$row->Confidence_387."</td>
       <td>".$row->SelectB_387."</td>
       <td>".$row->TimeB_387."</td>
       <td>".$row->SelectA_388."</td>
       <td>".$row->TimeA_388."</td>
       <td>".$row->Confidence_388."</td>
       <td>".$row->SelectB_388."</td>
       <td>".$row->TimeB_388."</td>
       <td>".$row->SelectA_389."</td>
       <td>".$row->TimeA_389."</td>
       <td>".$row->Confidence_389."</td>
       <td>".$row->SelectB_389."</td>
       <td>".$row->TimeB_389."</td>
       <td>".$row->SelectA_390."</td>
       <td>".$row->TimeA_390."</td>
       <td>".$row->Confidence_390."</td>
       <td>".$row->SelectB_390."</td>
       <td>".$row->TimeB_390."</td>
       <td>".$row->SelectA_391."</td>
       <td>".$row->TimeA_391."</td>
       <td>".$row->Confidence_391."</td>
       <td>".$row->SelectB_391."</td>
       <td>".$row->TimeB_391."</td>
       <td>".$row->SelectA_392."</td>
       <td>".$row->TimeA_392."</td>
       <td>".$row->Confidence_392."</td>
       <td>".$row->SelectB_392."</td>
       <td>".$row->TimeB_392."</td>
       <td>".$row->SelectA_393."</td>
       <td>".$row->TimeA_393."</td>
       <td>".$row->Confidence_393."</td>
       <td>".$row->SelectB_393."</td>
       <td>".$row->TimeB_393."</td>
       <td>".$row->SelectA_394."</td>
       <td>".$row->TimeA_394."</td>
       <td>".$row->Confidence_394."</td>
       <td>".$row->SelectB_394."</td>
       <td>".$row->TimeB_394."</td>
       <td>".$row->SelectA_395."</td>
       <td>".$row->TimeA_395."</td>
       <td>".$row->Confidence_395."</td>
       <td>".$row->SelectB_395."</td>
       <td>".$row->TimeB_395."</td>
       <td>".$row->SelectA_396."</td>
       <td>".$row->TimeA_396."</td>
       <td>".$row->Confidence_396."</td>
       <td>".$row->SelectB_396."</td>
       <td>".$row->TimeB_396."</td>
       <td>".$row->SelectA_397."</td>
       <td>".$row->TimeA_397."</td>
       <td>".$row->Confidence_397."</td>
       <td>".$row->SelectB_397."</td>
       <td>".$row->TimeB_397."</td>
       <td>".$row->SelectA_398."</td>
       <td>".$row->TimeA_398."</td>
       <td>".$row->Confidence_398."</td>
       <td>".$row->SelectB_398."</td>
       <td>".$row->TimeB_398."</td>
       <td>".$row->SelectA_399."</td>
       <td>".$row->TimeA_399."</td>
       <td>".$row->Confidence_399."</td>
       <td>".$row->SelectB_399."</td>
       <td>".$row->TimeB_399."</td>
       <td>".$row->SelectA_400."</td>
       <td>".$row->TimeA_400."</td>
       <td>".$row->Confidence_400."</td>
       <td>".$row->SelectB_400."</td>
       <td>".$row->TimeB_400."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";

echo $EXCEL_FILE;

?>
