<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=161; $k<241; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 161; $ii < 241; $ii++){
    $qry .= "a2.SelectA_".$ii.", a2.TimeA_".$ii.", a2.Confidence_".$ii.", b2.SelectB_".$ii.", b2.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_3 as a2, Data_B_3 as b2 where u.uid = a2.uid and u.uid = b2.uid";
$res = $mysqli->query($qry);

//echo $qry;

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_161."</td>
       <td>".$row->TimeA_161."</td>
       <td>".$row->Confidence_161."</td>
       <td>".$row->SelectB_161."</td>
       <td>".$row->TimeB_161."</td>
       <td>".$row->SelectA_162."</td>
       <td>".$row->TimeA_162."</td>
       <td>".$row->Confidence_162."</td>
       <td>".$row->SelectB_162."</td>
       <td>".$row->TimeB_162."</td>
       <td>".$row->SelectA_163."</td>
       <td>".$row->TimeA_163."</td>
       <td>".$row->Confidence_163."</td>
       <td>".$row->SelectB_163."</td>
       <td>".$row->TimeB_163."</td>
       <td>".$row->SelectA_164."</td>
       <td>".$row->TimeA_164."</td>
       <td>".$row->Confidence_164."</td>
       <td>".$row->SelectB_164."</td>
       <td>".$row->TimeB_164."</td>
       <td>".$row->SelectA_165."</td>
       <td>".$row->TimeA_165."</td>
       <td>".$row->Confidence_165."</td>
       <td>".$row->SelectB_165."</td>
       <td>".$row->TimeB_165."</td>
       <td>".$row->SelectA_166."</td>
       <td>".$row->TimeA_166."</td>
       <td>".$row->Confidence_166."</td>
       <td>".$row->SelectB_166."</td>
       <td>".$row->TimeB_166."</td>
       <td>".$row->SelectA_167."</td>
       <td>".$row->TimeA_167."</td>
       <td>".$row->Confidence_167."</td>
       <td>".$row->SelectB_167."</td>
       <td>".$row->TimeB_167."</td>
       <td>".$row->SelectA_168."</td>
       <td>".$row->TimeA_168."</td>
       <td>".$row->Confidence_168."</td>
       <td>".$row->SelectB_168."</td>
       <td>".$row->TimeB_168."</td>
       <td>".$row->SelectA_169."</td>
       <td>".$row->TimeA_169."</td>
       <td>".$row->Confidence_169."</td>
       <td>".$row->SelectB_169."</td>
       <td>".$row->TimeB_169."</td>
       <td>".$row->SelectA_170."</td>
       <td>".$row->TimeA_170."</td>
       <td>".$row->Confidence_170."</td>
       <td>".$row->SelectB_170."</td>
       <td>".$row->TimeB_170."</td>
       <td>".$row->SelectA_171."</td>
       <td>".$row->TimeA_171."</td>
       <td>".$row->Confidence_171."</td>
       <td>".$row->SelectB_171."</td>
       <td>".$row->TimeB_171."</td>
       <td>".$row->SelectA_172."</td>
       <td>".$row->TimeA_172."</td>
       <td>".$row->Confidence_172."</td>
       <td>".$row->SelectB_172."</td>
       <td>".$row->TimeB_172."</td>
       <td>".$row->SelectA_173."</td>
       <td>".$row->TimeA_173."</td>
       <td>".$row->Confidence_173."</td>
       <td>".$row->SelectB_173."</td>
       <td>".$row->TimeB_173."</td>
       <td>".$row->SelectA_174."</td>
       <td>".$row->TimeA_174."</td>
       <td>".$row->Confidence_174."</td>
       <td>".$row->SelectB_174."</td>
       <td>".$row->TimeB_174."</td>
       <td>".$row->SelectA_175."</td>
       <td>".$row->TimeA_175."</td>
       <td>".$row->Confidence_175."</td>
       <td>".$row->SelectB_175."</td>
       <td>".$row->TimeB_175."</td>
       <td>".$row->SelectA_176."</td>
       <td>".$row->TimeA_176."</td>
       <td>".$row->Confidence_176."</td>
       <td>".$row->SelectB_176."</td>
       <td>".$row->TimeB_176."</td>
       <td>".$row->SelectA_177."</td>
       <td>".$row->TimeA_177."</td>
       <td>".$row->Confidence_177."</td>
       <td>".$row->SelectB_177."</td>
       <td>".$row->TimeB_177."</td>
       <td>".$row->SelectA_178."</td>
       <td>".$row->TimeA_178."</td>
       <td>".$row->Confidence_178."</td>
       <td>".$row->SelectB_178."</td>
       <td>".$row->TimeB_178."</td>
       <td>".$row->SelectA_179."</td>
       <td>".$row->TimeA_179."</td>
       <td>".$row->Confidence_179."</td>
       <td>".$row->SelectB_179."</td>
       <td>".$row->TimeB_179."</td>
       <td>".$row->SelectA_180."</td>
       <td>".$row->TimeA_180."</td>
       <td>".$row->Confidence_180."</td>
       <td>".$row->SelectB_180."</td>
       <td>".$row->TimeB_180."</td>
       <td>".$row->SelectA_181."</td>
       <td>".$row->TimeA_181."</td>
       <td>".$row->Confidence_181."</td>
       <td>".$row->SelectB_181."</td>
       <td>".$row->TimeB_181."</td>
       <td>".$row->SelectA_182."</td>
       <td>".$row->TimeA_182."</td>
       <td>".$row->Confidence_182."</td>
       <td>".$row->SelectB_182."</td>
       <td>".$row->TimeB_182."</td>
       <td>".$row->SelectA_183."</td>
       <td>".$row->TimeA_183."</td>
       <td>".$row->Confidence_183."</td>
       <td>".$row->SelectB_183."</td>
       <td>".$row->TimeB_183."</td>
       <td>".$row->SelectA_184."</td>
       <td>".$row->TimeA_184."</td>
       <td>".$row->Confidence_184."</td>
       <td>".$row->SelectB_184."</td>
       <td>".$row->TimeB_184."</td>
       <td>".$row->SelectA_185."</td>
       <td>".$row->TimeA_185."</td>
       <td>".$row->Confidence_185."</td>
       <td>".$row->SelectB_185."</td>
       <td>".$row->TimeB_185."</td>
       <td>".$row->SelectA_186."</td>
       <td>".$row->TimeA_186."</td>
       <td>".$row->Confidence_186."</td>
       <td>".$row->SelectB_186."</td>
       <td>".$row->TimeB_186."</td>
       <td>".$row->SelectA_187."</td>
       <td>".$row->TimeA_187."</td>
       <td>".$row->Confidence_187."</td>
       <td>".$row->SelectB_187."</td>
       <td>".$row->TimeB_187."</td>
       <td>".$row->SelectA_188."</td>
       <td>".$row->TimeA_188."</td>
       <td>".$row->Confidence_188."</td>
       <td>".$row->SelectB_188."</td>
       <td>".$row->TimeB_188."</td>
       <td>".$row->SelectA_189."</td>
       <td>".$row->TimeA_189."</td>
       <td>".$row->Confidence_189."</td>
       <td>".$row->SelectB_189."</td>
       <td>".$row->TimeB_189."</td>
       <td>".$row->SelectA_190."</td>
       <td>".$row->TimeA_190."</td>
       <td>".$row->Confidence_190."</td>
       <td>".$row->SelectB_190."</td>
       <td>".$row->TimeB_190."</td>
       <td>".$row->SelectA_191."</td>
       <td>".$row->TimeA_191."</td>
       <td>".$row->Confidence_191."</td>
       <td>".$row->SelectB_191."</td>
       <td>".$row->TimeB_191."</td>
       <td>".$row->SelectA_192."</td>
       <td>".$row->TimeA_192."</td>
       <td>".$row->Confidence_192."</td>
       <td>".$row->SelectB_192."</td>
       <td>".$row->TimeB_192."</td>
       <td>".$row->SelectA_193."</td>
       <td>".$row->TimeA_193."</td>
       <td>".$row->Confidence_193."</td>
       <td>".$row->SelectB_193."</td>
       <td>".$row->TimeB_193."</td>
       <td>".$row->SelectA_194."</td>
       <td>".$row->TimeA_194."</td>
       <td>".$row->Confidence_194."</td>
       <td>".$row->SelectB_194."</td>
       <td>".$row->TimeB_194."</td>
       <td>".$row->SelectA_195."</td>
       <td>".$row->TimeA_195."</td>
       <td>".$row->Confidence_195."</td>
       <td>".$row->SelectB_195."</td>
       <td>".$row->TimeB_195."</td>
       <td>".$row->SelectA_196."</td>
       <td>".$row->TimeA_196."</td>
       <td>".$row->Confidence_196."</td>
       <td>".$row->SelectB_196."</td>
       <td>".$row->TimeB_196."</td>
       <td>".$row->SelectA_197."</td>
       <td>".$row->TimeA_197."</td>
       <td>".$row->Confidence_197."</td>
       <td>".$row->SelectB_197."</td>
       <td>".$row->TimeB_197."</td>
       <td>".$row->SelectA_198."</td>
       <td>".$row->TimeA_198."</td>
       <td>".$row->Confidence_198."</td>
       <td>".$row->SelectB_198."</td>
       <td>".$row->TimeB_198."</td>
       <td>".$row->SelectA_199."</td>
       <td>".$row->TimeA_199."</td>
       <td>".$row->Confidence_199."</td>
       <td>".$row->SelectB_199."</td>
       <td>".$row->TimeB_199."</td>
       <td>".$row->SelectA_200."</td>
       <td>".$row->TimeA_200."</td>
       <td>".$row->Confidence_200."</td>
       <td>".$row->SelectB_200."</td>
       <td>".$row->TimeB_200."</td>
       <td>".$row->SelectA_201."</td>
       <td>".$row->TimeA_201."</td>
       <td>".$row->Confidence_201."</td>
       <td>".$row->SelectB_201."</td>
       <td>".$row->TimeB_201."</td>
       <td>".$row->SelectA_202."</td>
       <td>".$row->TimeA_202."</td>
       <td>".$row->Confidence_202."</td>
       <td>".$row->SelectB_202."</td>
       <td>".$row->TimeB_202."</td>
       <td>".$row->SelectA_203."</td>
       <td>".$row->TimeA_203."</td>
       <td>".$row->Confidence_203."</td>
       <td>".$row->SelectB_203."</td>
       <td>".$row->TimeB_203."</td>
       <td>".$row->SelectA_204."</td>
       <td>".$row->TimeA_204."</td>
       <td>".$row->Confidence_204."</td>
       <td>".$row->SelectB_204."</td>
       <td>".$row->TimeB_204."</td>
       <td>".$row->SelectA_205."</td>
       <td>".$row->TimeA_205."</td>
       <td>".$row->Confidence_205."</td>
       <td>".$row->SelectB_205."</td>
       <td>".$row->TimeB_205."</td>
       <td>".$row->SelectA_206."</td>
       <td>".$row->TimeA_206."</td>
       <td>".$row->Confidence_206."</td>
       <td>".$row->SelectB_206."</td>
       <td>".$row->TimeB_206."</td>
       <td>".$row->SelectA_207."</td>
       <td>".$row->TimeA_207."</td>
       <td>".$row->Confidence_207."</td>
       <td>".$row->SelectB_207."</td>
       <td>".$row->TimeB_207."</td>
       <td>".$row->SelectA_208."</td>
       <td>".$row->TimeA_208."</td>
       <td>".$row->Confidence_208."</td>
       <td>".$row->SelectB_208."</td>
       <td>".$row->TimeB_208."</td>
       <td>".$row->SelectA_209."</td>
       <td>".$row->TimeA_209."</td>
       <td>".$row->Confidence_209."</td>
       <td>".$row->SelectB_209."</td>
       <td>".$row->TimeB_209."</td>
       <td>".$row->SelectA_210."</td>
       <td>".$row->TimeA_210."</td>
       <td>".$row->Confidence_210."</td>
       <td>".$row->SelectB_210."</td>
       <td>".$row->TimeB_210."</td>
       <td>".$row->SelectA_211."</td>
       <td>".$row->TimeA_211."</td>
       <td>".$row->Confidence_211."</td>
       <td>".$row->SelectB_211."</td>
       <td>".$row->TimeB_211."</td>
       <td>".$row->SelectA_212."</td>
       <td>".$row->TimeA_212."</td>
       <td>".$row->Confidence_212."</td>
       <td>".$row->SelectB_212."</td>
       <td>".$row->TimeB_212."</td>
       <td>".$row->SelectA_213."</td>
       <td>".$row->TimeA_213."</td>
       <td>".$row->Confidence_213."</td>
       <td>".$row->SelectB_213."</td>
       <td>".$row->TimeB_213."</td>
       <td>".$row->SelectA_214."</td>
       <td>".$row->TimeA_214."</td>
       <td>".$row->Confidence_214."</td>
       <td>".$row->SelectB_214."</td>
       <td>".$row->TimeB_214."</td>
       <td>".$row->SelectA_215."</td>
       <td>".$row->TimeA_215."</td>
       <td>".$row->Confidence_215."</td>
       <td>".$row->SelectB_215."</td>
       <td>".$row->TimeB_215."</td>
       <td>".$row->SelectA_216."</td>
       <td>".$row->TimeA_216."</td>
       <td>".$row->Confidence_216."</td>
       <td>".$row->SelectB_216."</td>
       <td>".$row->TimeB_216."</td>
       <td>".$row->SelectA_217."</td>
       <td>".$row->TimeA_217."</td>
       <td>".$row->Confidence_217."</td>
       <td>".$row->SelectB_217."</td>
       <td>".$row->TimeB_217."</td>
       <td>".$row->SelectA_218."</td>
       <td>".$row->TimeA_218."</td>
       <td>".$row->Confidence_218."</td>
       <td>".$row->SelectB_218."</td>
       <td>".$row->TimeB_218."</td>
       <td>".$row->SelectA_219."</td>
       <td>".$row->TimeA_219."</td>
       <td>".$row->Confidence_219."</td>
       <td>".$row->SelectB_219."</td>
       <td>".$row->TimeB_219."</td>
       <td>".$row->SelectA_220."</td>
       <td>".$row->TimeA_220."</td>
       <td>".$row->Confidence_220."</td>
       <td>".$row->SelectB_220."</td>
       <td>".$row->TimeB_220."</td>
       <td>".$row->SelectA_221."</td>
       <td>".$row->TimeA_221."</td>
       <td>".$row->Confidence_221."</td>
       <td>".$row->SelectB_221."</td>
       <td>".$row->TimeB_221."</td>
       <td>".$row->SelectA_222."</td>
       <td>".$row->TimeA_222."</td>
       <td>".$row->Confidence_222."</td>
       <td>".$row->SelectB_222."</td>
       <td>".$row->TimeB_222."</td>
       <td>".$row->SelectA_223."</td>
       <td>".$row->TimeA_223."</td>
       <td>".$row->Confidence_223."</td>
       <td>".$row->SelectB_223."</td>
       <td>".$row->TimeB_223."</td>
       <td>".$row->SelectA_224."</td>
       <td>".$row->TimeA_224."</td>
       <td>".$row->Confidence_224."</td>
       <td>".$row->SelectB_224."</td>
       <td>".$row->TimeB_224."</td>
       <td>".$row->SelectA_225."</td>
       <td>".$row->TimeA_225."</td>
       <td>".$row->Confidence_225."</td>
       <td>".$row->SelectB_225."</td>
       <td>".$row->TimeB_225."</td>
       <td>".$row->SelectA_226."</td>
       <td>".$row->TimeA_226."</td>
       <td>".$row->Confidence_226."</td>
       <td>".$row->SelectB_226."</td>
       <td>".$row->TimeB_226."</td>
       <td>".$row->SelectA_227."</td>
       <td>".$row->TimeA_227."</td>
       <td>".$row->Confidence_227."</td>
       <td>".$row->SelectB_227."</td>
       <td>".$row->TimeB_227."</td>
       <td>".$row->SelectA_228."</td>
       <td>".$row->TimeA_228."</td>
       <td>".$row->Confidence_228."</td>
       <td>".$row->SelectB_228."</td>
       <td>".$row->TimeB_228."</td>
       <td>".$row->SelectA_229."</td>
       <td>".$row->TimeA_229."</td>
       <td>".$row->Confidence_229."</td>
       <td>".$row->SelectB_229."</td>
       <td>".$row->TimeB_229."</td>
       <td>".$row->SelectA_230."</td>
       <td>".$row->TimeA_230."</td>
       <td>".$row->Confidence_230."</td>
       <td>".$row->SelectB_230."</td>
       <td>".$row->TimeB_230."</td>
       <td>".$row->SelectA_231."</td>
       <td>".$row->TimeA_231."</td>
       <td>".$row->Confidence_231."</td>
       <td>".$row->SelectB_231."</td>
       <td>".$row->TimeB_231."</td>
       <td>".$row->SelectA_232."</td>
       <td>".$row->TimeA_232."</td>
       <td>".$row->Confidence_232."</td>
       <td>".$row->SelectB_232."</td>
       <td>".$row->TimeB_232."</td>
       <td>".$row->SelectA_233."</td>
       <td>".$row->TimeA_233."</td>
       <td>".$row->Confidence_233."</td>
       <td>".$row->SelectB_233."</td>
       <td>".$row->TimeB_233."</td>
       <td>".$row->SelectA_234."</td>
       <td>".$row->TimeA_234."</td>
       <td>".$row->Confidence_234."</td>
       <td>".$row->SelectB_234."</td>
       <td>".$row->TimeB_234."</td>
       <td>".$row->SelectA_235."</td>
       <td>".$row->TimeA_235."</td>
       <td>".$row->Confidence_235."</td>
       <td>".$row->SelectB_235."</td>
       <td>".$row->TimeB_235."</td>
       <td>".$row->SelectA_236."</td>
       <td>".$row->TimeA_236."</td>
       <td>".$row->Confidence_236."</td>
       <td>".$row->SelectB_236."</td>
       <td>".$row->TimeB_236."</td>
       <td>".$row->SelectA_237."</td>
       <td>".$row->TimeA_237."</td>
       <td>".$row->Confidence_237."</td>
       <td>".$row->SelectB_237."</td>
       <td>".$row->TimeB_237."</td>
       <td>".$row->SelectA_238."</td>
       <td>".$row->TimeA_238."</td>
       <td>".$row->Confidence_238."</td>
       <td>".$row->SelectB_238."</td>
       <td>".$row->TimeB_238."</td>
       <td>".$row->SelectA_239."</td>
       <td>".$row->TimeA_239."</td>
       <td>".$row->Confidence_239."</td>
       <td>".$row->SelectB_239."</td>
       <td>".$row->TimeB_239."</td>
       <td>".$row->SelectA_240."</td>
       <td>".$row->TimeA_240."</td>
       <td>".$row->Confidence_240."</td>
       <td>".$row->SelectB_240."</td>
       <td>".$row->TimeB_240."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";

echo $EXCEL_FILE;

?>
