<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=641; $k<721; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 641; $ii < 721; $ii++){
    $qry .= "a2.SelectA_".$ii.", a2.TimeA_".$ii.", a2.Confidence_".$ii.", b2.SelectB_".$ii.", b2.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_9 as a2, Data_B_9 as b2 where u.uid = a2.uid and u.uid = b2.uid";
$res = $mysqli->query($qry);

//echo $qry;

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_641."</td>
       <td>".$row->TimeA_641."</td>
       <td>".$row->Confidence_641."</td>
       <td>".$row->SelectB_641."</td>
       <td>".$row->TimeB_641."</td>
       <td>".$row->SelectA_642."</td>
       <td>".$row->TimeA_642."</td>
       <td>".$row->Confidence_642."</td>
       <td>".$row->SelectB_642."</td>
       <td>".$row->TimeB_642."</td>
       <td>".$row->SelectA_643."</td>
       <td>".$row->TimeA_643."</td>
       <td>".$row->Confidence_643."</td>
       <td>".$row->SelectB_643."</td>
       <td>".$row->TimeB_643."</td>
       <td>".$row->SelectA_644."</td>
       <td>".$row->TimeA_644."</td>
       <td>".$row->Confidence_644."</td>
       <td>".$row->SelectB_644."</td>
       <td>".$row->TimeB_644."</td>
       <td>".$row->SelectA_645."</td>
       <td>".$row->TimeA_645."</td>
       <td>".$row->Confidence_645."</td>
       <td>".$row->SelectB_645."</td>
       <td>".$row->TimeB_645."</td>
       <td>".$row->SelectA_646."</td>
       <td>".$row->TimeA_646."</td>
       <td>".$row->Confidence_646."</td>
       <td>".$row->SelectB_646."</td>
       <td>".$row->TimeB_646."</td>
       <td>".$row->SelectA_647."</td>
       <td>".$row->TimeA_647."</td>
       <td>".$row->Confidence_647."</td>
       <td>".$row->SelectB_647."</td>
       <td>".$row->TimeB_647."</td>
       <td>".$row->SelectA_648."</td>
       <td>".$row->TimeA_648."</td>
       <td>".$row->Confidence_648."</td>
       <td>".$row->SelectB_648."</td>
       <td>".$row->TimeB_648."</td>
       <td>".$row->SelectA_649."</td>
       <td>".$row->TimeA_649."</td>
       <td>".$row->Confidence_649."</td>
       <td>".$row->SelectB_649."</td>
       <td>".$row->TimeB_649."</td>
       <td>".$row->SelectA_650."</td>
       <td>".$row->TimeA_650."</td>
       <td>".$row->Confidence_650."</td>
       <td>".$row->SelectB_650."</td>
       <td>".$row->TimeB_650."</td>
       <td>".$row->SelectA_651."</td>
       <td>".$row->TimeA_651."</td>
       <td>".$row->Confidence_651."</td>
       <td>".$row->SelectB_651."</td>
       <td>".$row->TimeB_651."</td>
       <td>".$row->SelectA_652."</td>
       <td>".$row->TimeA_652."</td>
       <td>".$row->Confidence_652."</td>
       <td>".$row->SelectB_652."</td>
       <td>".$row->TimeB_652."</td>
       <td>".$row->SelectA_653."</td>
       <td>".$row->TimeA_653."</td>
       <td>".$row->Confidence_653."</td>
       <td>".$row->SelectB_653."</td>
       <td>".$row->TimeB_653."</td>
       <td>".$row->SelectA_654."</td>
       <td>".$row->TimeA_654."</td>
       <td>".$row->Confidence_654."</td>
       <td>".$row->SelectB_654."</td>
       <td>".$row->TimeB_654."</td>
       <td>".$row->SelectA_655."</td>
       <td>".$row->TimeA_655."</td>
       <td>".$row->Confidence_655."</td>
       <td>".$row->SelectB_655."</td>
       <td>".$row->TimeB_655."</td>
       <td>".$row->SelectA_656."</td>
       <td>".$row->TimeA_656."</td>
       <td>".$row->Confidence_656."</td>
       <td>".$row->SelectB_656."</td>
       <td>".$row->TimeB_656."</td>
       <td>".$row->SelectA_657."</td>
       <td>".$row->TimeA_657."</td>
       <td>".$row->Confidence_657."</td>
       <td>".$row->SelectB_657."</td>
       <td>".$row->TimeB_657."</td>
       <td>".$row->SelectA_658."</td>
       <td>".$row->TimeA_658."</td>
       <td>".$row->Confidence_658."</td>
       <td>".$row->SelectB_658."</td>
       <td>".$row->TimeB_658."</td>
       <td>".$row->SelectA_659."</td>
       <td>".$row->TimeA_659."</td>
       <td>".$row->Confidence_659."</td>
       <td>".$row->SelectB_659."</td>
       <td>".$row->TimeB_659."</td>
       <td>".$row->SelectA_660."</td>
       <td>".$row->TimeA_660."</td>
       <td>".$row->Confidence_660."</td>
       <td>".$row->SelectB_660."</td>
       <td>".$row->TimeB_660."</td>
       <td>".$row->SelectA_661."</td>
       <td>".$row->TimeA_661."</td>
       <td>".$row->Confidence_661."</td>
       <td>".$row->SelectB_661."</td>
       <td>".$row->TimeB_661."</td>
       <td>".$row->SelectA_662."</td>
       <td>".$row->TimeA_662."</td>
       <td>".$row->Confidence_662."</td>
       <td>".$row->SelectB_662."</td>
       <td>".$row->TimeB_662."</td>
       <td>".$row->SelectA_663."</td>
       <td>".$row->TimeA_663."</td>
       <td>".$row->Confidence_663."</td>
       <td>".$row->SelectB_663."</td>
       <td>".$row->TimeB_663."</td>
       <td>".$row->SelectA_664."</td>
       <td>".$row->TimeA_664."</td>
       <td>".$row->Confidence_664."</td>
       <td>".$row->SelectB_664."</td>
       <td>".$row->TimeB_664."</td>
       <td>".$row->SelectA_665."</td>
       <td>".$row->TimeA_665."</td>
       <td>".$row->Confidence_665."</td>
       <td>".$row->SelectB_665."</td>
       <td>".$row->TimeB_665."</td>
       <td>".$row->SelectA_666."</td>
       <td>".$row->TimeA_666."</td>
       <td>".$row->Confidence_666."</td>
       <td>".$row->SelectB_666."</td>
       <td>".$row->TimeB_666."</td>
       <td>".$row->SelectA_667."</td>
       <td>".$row->TimeA_667."</td>
       <td>".$row->Confidence_667."</td>
       <td>".$row->SelectB_667."</td>
       <td>".$row->TimeB_667."</td>
       <td>".$row->SelectA_668."</td>
       <td>".$row->TimeA_668."</td>
       <td>".$row->Confidence_668."</td>
       <td>".$row->SelectB_668."</td>
       <td>".$row->TimeB_668."</td>
       <td>".$row->SelectA_669."</td>
       <td>".$row->TimeA_669."</td>
       <td>".$row->Confidence_669."</td>
       <td>".$row->SelectB_669."</td>
       <td>".$row->TimeB_669."</td>
       <td>".$row->SelectA_670."</td>
       <td>".$row->TimeA_670."</td>
       <td>".$row->Confidence_670."</td>
       <td>".$row->SelectB_670."</td>
       <td>".$row->TimeB_670."</td>
       <td>".$row->SelectA_671."</td>
       <td>".$row->TimeA_671."</td>
       <td>".$row->Confidence_671."</td>
       <td>".$row->SelectB_671."</td>
       <td>".$row->TimeB_671."</td>
       <td>".$row->SelectA_672."</td>
       <td>".$row->TimeA_672."</td>
       <td>".$row->Confidence_672."</td>
       <td>".$row->SelectB_672."</td>
       <td>".$row->TimeB_672."</td>
       <td>".$row->SelectA_673."</td>
       <td>".$row->TimeA_673."</td>
       <td>".$row->Confidence_673."</td>
       <td>".$row->SelectB_673."</td>
       <td>".$row->TimeB_673."</td>
       <td>".$row->SelectA_674."</td>
       <td>".$row->TimeA_674."</td>
       <td>".$row->Confidence_674."</td>
       <td>".$row->SelectB_674."</td>
       <td>".$row->TimeB_674."</td>
       <td>".$row->SelectA_675."</td>
       <td>".$row->TimeA_675."</td>
       <td>".$row->Confidence_675."</td>
       <td>".$row->SelectB_675."</td>
       <td>".$row->TimeB_675."</td>
       <td>".$row->SelectA_676."</td>
       <td>".$row->TimeA_676."</td>
       <td>".$row->Confidence_676."</td>
       <td>".$row->SelectB_676."</td>
       <td>".$row->TimeB_676."</td>
       <td>".$row->SelectA_677."</td>
       <td>".$row->TimeA_677."</td>
       <td>".$row->Confidence_677."</td>
       <td>".$row->SelectB_677."</td>
       <td>".$row->TimeB_677."</td>
       <td>".$row->SelectA_678."</td>
       <td>".$row->TimeA_678."</td>
       <td>".$row->Confidence_678."</td>
       <td>".$row->SelectB_678."</td>
       <td>".$row->TimeB_678."</td>
       <td>".$row->SelectA_679."</td>
       <td>".$row->TimeA_679."</td>
       <td>".$row->Confidence_679."</td>
       <td>".$row->SelectB_679."</td>
       <td>".$row->TimeB_679."</td>
       <td>".$row->SelectA_680."</td>
       <td>".$row->TimeA_680."</td>
       <td>".$row->Confidence_680."</td>
       <td>".$row->SelectB_680."</td>
       <td>".$row->TimeB_680."</td>
       <td>".$row->SelectA_681."</td>
       <td>".$row->TimeA_681."</td>
       <td>".$row->Confidence_681."</td>
       <td>".$row->SelectB_681."</td>
       <td>".$row->TimeB_681."</td>
       <td>".$row->SelectA_682."</td>
       <td>".$row->TimeA_682."</td>
       <td>".$row->Confidence_682."</td>
       <td>".$row->SelectB_682."</td>
       <td>".$row->TimeB_682."</td>
       <td>".$row->SelectA_683."</td>
       <td>".$row->TimeA_683."</td>
       <td>".$row->Confidence_683."</td>
       <td>".$row->SelectB_683."</td>
       <td>".$row->TimeB_683."</td>
       <td>".$row->SelectA_684."</td>
       <td>".$row->TimeA_684."</td>
       <td>".$row->Confidence_684."</td>
       <td>".$row->SelectB_684."</td>
       <td>".$row->TimeB_684."</td>
       <td>".$row->SelectA_685."</td>
       <td>".$row->TimeA_685."</td>
       <td>".$row->Confidence_685."</td>
       <td>".$row->SelectB_685."</td>
       <td>".$row->TimeB_685."</td>
       <td>".$row->SelectA_686."</td>
       <td>".$row->TimeA_686."</td>
       <td>".$row->Confidence_686."</td>
       <td>".$row->SelectB_686."</td>
       <td>".$row->TimeB_686."</td>
       <td>".$row->SelectA_687."</td>
       <td>".$row->TimeA_687."</td>
       <td>".$row->Confidence_687."</td>
       <td>".$row->SelectB_687."</td>
       <td>".$row->TimeB_687."</td>
       <td>".$row->SelectA_688."</td>
       <td>".$row->TimeA_688."</td>
       <td>".$row->Confidence_688."</td>
       <td>".$row->SelectB_688."</td>
       <td>".$row->TimeB_688."</td>
       <td>".$row->SelectA_689."</td>
       <td>".$row->TimeA_689."</td>
       <td>".$row->Confidence_689."</td>
       <td>".$row->SelectB_689."</td>
       <td>".$row->TimeB_689."</td>
       <td>".$row->SelectA_690."</td>
       <td>".$row->TimeA_690."</td>
       <td>".$row->Confidence_690."</td>
       <td>".$row->SelectB_690."</td>
       <td>".$row->TimeB_690."</td>
       <td>".$row->SelectA_691."</td>
       <td>".$row->TimeA_691."</td>
       <td>".$row->Confidence_691."</td>
       <td>".$row->SelectB_691."</td>
       <td>".$row->TimeB_691."</td>
       <td>".$row->SelectA_692."</td>
       <td>".$row->TimeA_692."</td>
       <td>".$row->Confidence_692."</td>
       <td>".$row->SelectB_692."</td>
       <td>".$row->TimeB_692."</td>
       <td>".$row->SelectA_693."</td>
       <td>".$row->TimeA_693."</td>
       <td>".$row->Confidence_693."</td>
       <td>".$row->SelectB_693."</td>
       <td>".$row->TimeB_693."</td>
       <td>".$row->SelectA_694."</td>
       <td>".$row->TimeA_694."</td>
       <td>".$row->Confidence_694."</td>
       <td>".$row->SelectB_694."</td>
       <td>".$row->TimeB_694."</td>
       <td>".$row->SelectA_695."</td>
       <td>".$row->TimeA_695."</td>
       <td>".$row->Confidence_695."</td>
       <td>".$row->SelectB_695."</td>
       <td>".$row->TimeB_695."</td>
       <td>".$row->SelectA_696."</td>
       <td>".$row->TimeA_696."</td>
       <td>".$row->Confidence_696."</td>
       <td>".$row->SelectB_696."</td>
       <td>".$row->TimeB_696."</td>
       <td>".$row->SelectA_697."</td>
       <td>".$row->TimeA_697."</td>
       <td>".$row->Confidence_697."</td>
       <td>".$row->SelectB_697."</td>
       <td>".$row->TimeB_697."</td>
       <td>".$row->SelectA_698."</td>
       <td>".$row->TimeA_698."</td>
       <td>".$row->Confidence_698."</td>
       <td>".$row->SelectB_698."</td>
       <td>".$row->TimeB_698."</td>
       <td>".$row->SelectA_699."</td>
       <td>".$row->TimeA_699."</td>
       <td>".$row->Confidence_699."</td>
       <td>".$row->SelectB_699."</td>
       <td>".$row->TimeB_699."</td>
       <td>".$row->SelectA_700."</td>
       <td>".$row->TimeA_700."</td>
       <td>".$row->Confidence_700."</td>
       <td>".$row->SelectB_700."</td>
       <td>".$row->TimeB_700."</td>
       <td>".$row->SelectA_701."</td>
       <td>".$row->TimeA_701."</td>
       <td>".$row->Confidence_701."</td>
       <td>".$row->SelectB_701."</td>
       <td>".$row->TimeB_701."</td>
       <td>".$row->SelectA_702."</td>
       <td>".$row->TimeA_702."</td>
       <td>".$row->Confidence_702."</td>
       <td>".$row->SelectB_702."</td>
       <td>".$row->TimeB_702."</td>
       <td>".$row->SelectA_703."</td>
       <td>".$row->TimeA_703."</td>
       <td>".$row->Confidence_703."</td>
       <td>".$row->SelectB_703."</td>
       <td>".$row->TimeB_703."</td>
       <td>".$row->SelectA_704."</td>
       <td>".$row->TimeA_704."</td>
       <td>".$row->Confidence_704."</td>
       <td>".$row->SelectB_704."</td>
       <td>".$row->TimeB_704."</td>
       <td>".$row->SelectA_705."</td>
       <td>".$row->TimeA_705."</td>
       <td>".$row->Confidence_705."</td>
       <td>".$row->SelectB_705."</td>
       <td>".$row->TimeB_705."</td>
       <td>".$row->SelectA_706."</td>
       <td>".$row->TimeA_706."</td>
       <td>".$row->Confidence_706."</td>
       <td>".$row->SelectB_706."</td>
       <td>".$row->TimeB_706."</td>
       <td>".$row->SelectA_707."</td>
       <td>".$row->TimeA_707."</td>
       <td>".$row->Confidence_707."</td>
       <td>".$row->SelectB_707."</td>
       <td>".$row->TimeB_707."</td>
       <td>".$row->SelectA_708."</td>
       <td>".$row->TimeA_708."</td>
       <td>".$row->Confidence_708."</td>
       <td>".$row->SelectB_708."</td>
       <td>".$row->TimeB_708."</td>
       <td>".$row->SelectA_709."</td>
       <td>".$row->TimeA_709."</td>
       <td>".$row->Confidence_709."</td>
       <td>".$row->SelectB_709."</td>
       <td>".$row->TimeB_709."</td>
       <td>".$row->SelectA_710."</td>
       <td>".$row->TimeA_710."</td>
       <td>".$row->Confidence_710."</td>
       <td>".$row->SelectB_710."</td>
       <td>".$row->TimeB_710."</td>
       <td>".$row->SelectA_711."</td>
       <td>".$row->TimeA_711."</td>
       <td>".$row->Confidence_711."</td>
       <td>".$row->SelectB_711."</td>
       <td>".$row->TimeB_711."</td>
       <td>".$row->SelectA_712."</td>
       <td>".$row->TimeA_712."</td>
       <td>".$row->Confidence_712."</td>
       <td>".$row->SelectB_712."</td>
       <td>".$row->TimeB_712."</td>
       <td>".$row->SelectA_713."</td>
       <td>".$row->TimeA_713."</td>
       <td>".$row->Confidence_713."</td>
       <td>".$row->SelectB_713."</td>
       <td>".$row->TimeB_713."</td>
       <td>".$row->SelectA_714."</td>
       <td>".$row->TimeA_714."</td>
       <td>".$row->Confidence_714."</td>
       <td>".$row->SelectB_714."</td>
       <td>".$row->TimeB_714."</td>
       <td>".$row->SelectA_715."</td>
       <td>".$row->TimeA_715."</td>
       <td>".$row->Confidence_715."</td>
       <td>".$row->SelectB_715."</td>
       <td>".$row->TimeB_715."</td>
       <td>".$row->SelectA_716."</td>
       <td>".$row->TimeA_716."</td>
       <td>".$row->Confidence_716."</td>
       <td>".$row->SelectB_716."</td>
       <td>".$row->TimeB_716."</td>
       <td>".$row->SelectA_717."</td>
       <td>".$row->TimeA_717."</td>
       <td>".$row->Confidence_717."</td>
       <td>".$row->SelectB_717."</td>
       <td>".$row->TimeB_717."</td>
       <td>".$row->SelectA_718."</td>
       <td>".$row->TimeA_718."</td>
       <td>".$row->Confidence_718."</td>
       <td>".$row->SelectB_718."</td>
       <td>".$row->TimeB_718."</td>
       <td>".$row->SelectA_719."</td>
       <td>".$row->TimeA_719."</td>
       <td>".$row->Confidence_719."</td>
       <td>".$row->SelectB_719."</td>
       <td>".$row->TimeB_719."</td>
       <td>".$row->SelectA_720."</td>
       <td>".$row->TimeA_720."</td>
       <td>".$row->Confidence_720."</td>
       <td>".$row->SelectB_720."</td>
       <td>".$row->TimeB_720."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";

echo $EXCEL_FILE;

?>
