<?php
include ("conn/conn.php");

header( "Content-type: application/vnd.ms-excel; charset=utf-8");
header( "Content-Disposition: attachment; filename = main_test.xls" );
header( "Content-Description: PHP4 Generated Data" );

$EXCEL_FILE = "

<table border='1'>
    <tr>
       <td>유저식별아이디</td>
       <td>나이</td>
       <td>성별</td>
       <td>학력</td>
       <td>시력</td>
       <td>참여일자</td>
       <td>MC구분</td>
";

for($k=1; $k<81; $k++){
    $EXCEL_FILE .= "       
       <td>선택_A_".$k."</td>
       <td>시간_A_".$k."</td>
       <td>확신_".$k."</td>
       <td>선택_B_".$k."</td>
       <td>시간_B_".$k."</td>
    ";
}
"</tr>";


$qry = "SELECT u.uid, u.Age, u.Gender, u.Grade, u.Sight, u.SelectMC, ";
for($ii = 1; $ii < 81; $ii++){
    $qry .= "a1.SelectA_".$ii.", a1.TimeA_".$ii.", a1.Confidence_".$ii.", b1.SelectB_".$ii.", b1.TimeB_".$ii.",";
}
$qry .= "u.S_time from Data_Users as u, Data_A_1 as a1, Data_B_1 as b1 where u.uid = a1.uid and u.uid = b1.uid";
$res = $mysqli->query($qry);

while ($row = $res->fetch_object()) {

    $EXCEL_FILE .= "

    <tr>
       <td>".$row->uid."</td>
       <td>".$row->Age."</td>
       <td>".$row->Gender."</td>
       <td>".$row->Grade."</td>
       <td>".$row->Sight."</td>
       <td>".$row->S_time."</td>
       <td>".$row->SelectMC."</td>
       <td>".$row->SelectA_1."</td>
       <td>".$row->TimeA_1."</td>
       <td>".$row->Confidence_1."</td>
       <td>".$row->SelectB_1."</td>
       <td>".$row->TimeB_1."</td>
       <td>".$row->SelectA_2."</td>
       <td>".$row->TimeA_2."</td>
       <td>".$row->Confidence_2."</td>
       <td>".$row->SelectB_2."</td>
       <td>".$row->TimeB_2."</td>
       <td>".$row->SelectA_3."</td>
       <td>".$row->TimeA_3."</td>
       <td>".$row->Confidence_3."</td>
       <td>".$row->SelectB_3."</td>
       <td>".$row->TimeB_3."</td>
       <td>".$row->SelectA_4."</td>
       <td>".$row->TimeA_4."</td>
       <td>".$row->Confidence_4."</td>
       <td>".$row->SelectB_4."</td>
       <td>".$row->TimeB_4."</td>
       <td>".$row->SelectA_5."</td>
       <td>".$row->TimeA_5."</td>
       <td>".$row->Confidence_5."</td>
       <td>".$row->SelectB_5."</td>
       <td>".$row->TimeB_5."</td>
       <td>".$row->SelectA_6."</td>
       <td>".$row->TimeA_6."</td>
       <td>".$row->Confidence_6."</td>
       <td>".$row->SelectB_6."</td>
       <td>".$row->TimeB_6."</td>
       <td>".$row->SelectA_7."</td>
       <td>".$row->TimeA_7."</td>
       <td>".$row->Confidence_7."</td>
       <td>".$row->SelectB_7."</td>
       <td>".$row->TimeB_7."</td>
       <td>".$row->SelectA_8."</td>
       <td>".$row->TimeA_8."</td>
       <td>".$row->Confidence_8."</td>
       <td>".$row->SelectB_8."</td>
       <td>".$row->TimeB_8."</td>
       <td>".$row->SelectA_9."</td>
       <td>".$row->TimeA_9."</td>
       <td>".$row->Confidence_9."</td>
       <td>".$row->SelectB_9."</td>
       <td>".$row->TimeB_9."</td>
       <td>".$row->SelectA_10."</td>
       <td>".$row->TimeA_10."</td>
       <td>".$row->Confidence_10."</td>
       <td>".$row->SelectB_10."</td>
       <td>".$row->TimeB_10."</td>
       <td>".$row->SelectA_11."</td>
       <td>".$row->TimeA_11."</td>
       <td>".$row->Confidence_11."</td>
       <td>".$row->SelectB_11."</td>
       <td>".$row->TimeB_11."</td>
       <td>".$row->SelectA_12."</td>
       <td>".$row->TimeA_12."</td>
       <td>".$row->Confidence_12."</td>
       <td>".$row->SelectB_12."</td>
       <td>".$row->TimeB_12."</td>
       <td>".$row->SelectA_13."</td>
       <td>".$row->TimeA_13."</td>
       <td>".$row->Confidence_13."</td>
       <td>".$row->SelectB_13."</td>
       <td>".$row->TimeB_13."</td>
       <td>".$row->SelectA_14."</td>
       <td>".$row->TimeA_14."</td>
       <td>".$row->Confidence_14."</td>
       <td>".$row->SelectB_14."</td>
       <td>".$row->TimeB_14."</td>
       <td>".$row->SelectA_15."</td>
       <td>".$row->TimeA_15."</td>
       <td>".$row->Confidence_15."</td>
       <td>".$row->SelectB_15."</td>
       <td>".$row->TimeB_15."</td>
       <td>".$row->SelectA_16."</td>
       <td>".$row->TimeA_16."</td>
       <td>".$row->Confidence_16."</td>
       <td>".$row->SelectB_16."</td>
       <td>".$row->TimeB_16."</td>
       <td>".$row->SelectA_17."</td>
       <td>".$row->TimeA_17."</td>
       <td>".$row->Confidence_17."</td>
       <td>".$row->SelectB_17."</td>
       <td>".$row->TimeB_17."</td>
       <td>".$row->SelectA_18."</td>
       <td>".$row->TimeA_18."</td>
       <td>".$row->Confidence_18."</td>
       <td>".$row->SelectB_18."</td>
       <td>".$row->TimeB_18."</td>
       <td>".$row->SelectA_19."</td>
       <td>".$row->TimeA_19."</td>
       <td>".$row->Confidence_19."</td>
       <td>".$row->SelectB_19."</td>
       <td>".$row->TimeB_19."</td>
       <td>".$row->SelectA_20."</td>
       <td>".$row->TimeA_20."</td>
       <td>".$row->Confidence_20."</td>
       <td>".$row->SelectB_20."</td>
       <td>".$row->TimeB_20."</td>
       <td>".$row->SelectA_21."</td>
       <td>".$row->TimeA_21."</td>
       <td>".$row->Confidence_21."</td>
       <td>".$row->SelectB_21."</td>
       <td>".$row->TimeB_21."</td>
       <td>".$row->SelectA_22."</td>
       <td>".$row->TimeA_22."</td>
       <td>".$row->Confidence_22."</td>
       <td>".$row->SelectB_22."</td>
       <td>".$row->TimeB_22."</td>
       <td>".$row->SelectA_23."</td>
       <td>".$row->TimeA_23."</td>
       <td>".$row->Confidence_23."</td>
       <td>".$row->SelectB_23."</td>
       <td>".$row->TimeB_23."</td>
       <td>".$row->SelectA_24."</td>
       <td>".$row->TimeA_24."</td>
       <td>".$row->Confidence_24."</td>
       <td>".$row->SelectB_24."</td>
       <td>".$row->TimeB_24."</td>
       <td>".$row->SelectA_25."</td>
       <td>".$row->TimeA_25."</td>
       <td>".$row->Confidence_25."</td>
       <td>".$row->SelectB_25."</td>
       <td>".$row->TimeB_25."</td>
       <td>".$row->SelectA_26."</td>
       <td>".$row->TimeA_26."</td>
       <td>".$row->Confidence_26."</td>
       <td>".$row->SelectB_26."</td>
       <td>".$row->TimeB_26."</td>
       <td>".$row->SelectA_27."</td>
       <td>".$row->TimeA_27."</td>
       <td>".$row->Confidence_27."</td>
       <td>".$row->SelectB_27."</td>
       <td>".$row->TimeB_27."</td>
       <td>".$row->SelectA_28."</td>
       <td>".$row->TimeA_28."</td>
       <td>".$row->Confidence_28."</td>
       <td>".$row->SelectB_28."</td>
       <td>".$row->TimeB_28."</td>
       <td>".$row->SelectA_29."</td>
       <td>".$row->TimeA_29."</td>
       <td>".$row->Confidence_29."</td>
       <td>".$row->SelectB_29."</td>
       <td>".$row->TimeB_29."</td>
       <td>".$row->SelectA_30."</td>
       <td>".$row->TimeA_30."</td>
       <td>".$row->Confidence_30."</td>
       <td>".$row->SelectB_30."</td>
       <td>".$row->TimeB_30."</td>
       <td>".$row->SelectA_31."</td>
       <td>".$row->TimeA_31."</td>
       <td>".$row->Confidence_31."</td>
       <td>".$row->SelectB_31."</td>
       <td>".$row->TimeB_31."</td>
       <td>".$row->SelectA_32."</td>
       <td>".$row->TimeA_32."</td>
       <td>".$row->Confidence_32."</td>
       <td>".$row->SelectB_32."</td>
       <td>".$row->TimeB_32."</td>
       <td>".$row->SelectA_33."</td>
       <td>".$row->TimeA_33."</td>
       <td>".$row->Confidence_33."</td>
       <td>".$row->SelectB_33."</td>
       <td>".$row->TimeB_33."</td>
       <td>".$row->SelectA_34."</td>
       <td>".$row->TimeA_34."</td>
       <td>".$row->Confidence_34."</td>
       <td>".$row->SelectB_34."</td>
       <td>".$row->TimeB_34."</td>
       <td>".$row->SelectA_35."</td>
       <td>".$row->TimeA_35."</td>
       <td>".$row->Confidence_35."</td>
       <td>".$row->SelectB_35."</td>
       <td>".$row->TimeB_35."</td>
       <td>".$row->SelectA_36."</td>
       <td>".$row->TimeA_36."</td>
       <td>".$row->Confidence_36."</td>
       <td>".$row->SelectB_36."</td>
       <td>".$row->TimeB_36."</td>
       <td>".$row->SelectA_37."</td>
       <td>".$row->TimeA_37."</td>
       <td>".$row->Confidence_37."</td>
       <td>".$row->SelectB_37."</td>
       <td>".$row->TimeB_37."</td>
       <td>".$row->SelectA_38."</td>
       <td>".$row->TimeA_38."</td>
       <td>".$row->Confidence_38."</td>
       <td>".$row->SelectB_38."</td>
       <td>".$row->TimeB_38."</td>
       <td>".$row->SelectA_39."</td>
       <td>".$row->TimeA_39."</td>
       <td>".$row->Confidence_39."</td>
       <td>".$row->SelectB_39."</td>
       <td>".$row->TimeB_39."</td>
       <td>".$row->SelectA_40."</td>
       <td>".$row->TimeA_40."</td>
       <td>".$row->Confidence_40."</td>
       <td>".$row->SelectB_40."</td>
       <td>".$row->TimeB_40."</td>
       <td>".$row->SelectA_41."</td>
       <td>".$row->TimeA_41."</td>
       <td>".$row->Confidence_41."</td>
       <td>".$row->SelectB_41."</td>
       <td>".$row->TimeB_41."</td>
       <td>".$row->SelectA_42."</td>
       <td>".$row->TimeA_42."</td>
       <td>".$row->Confidence_42."</td>
       <td>".$row->SelectB_42."</td>
       <td>".$row->TimeB_42."</td>
       <td>".$row->SelectA_43."</td>
       <td>".$row->TimeA_43."</td>
       <td>".$row->Confidence_43."</td>
       <td>".$row->SelectB_43."</td>
       <td>".$row->TimeB_43."</td>
       <td>".$row->SelectA_44."</td>
       <td>".$row->TimeA_44."</td>
       <td>".$row->Confidence_44."</td>
       <td>".$row->SelectB_44."</td>
       <td>".$row->TimeB_44."</td>
       <td>".$row->SelectA_45."</td>
       <td>".$row->TimeA_45."</td>
       <td>".$row->Confidence_45."</td>
       <td>".$row->SelectB_45."</td>
       <td>".$row->TimeB_45."</td>
       <td>".$row->SelectA_46."</td>
       <td>".$row->TimeA_46."</td>
       <td>".$row->Confidence_46."</td>
       <td>".$row->SelectB_46."</td>
       <td>".$row->TimeB_46."</td>
       <td>".$row->SelectA_47."</td>
       <td>".$row->TimeA_47."</td>
       <td>".$row->Confidence_47."</td>
       <td>".$row->SelectB_47."</td>
       <td>".$row->TimeB_47."</td>
       <td>".$row->SelectA_48."</td>
       <td>".$row->TimeA_48."</td>
       <td>".$row->Confidence_48."</td>
       <td>".$row->SelectB_48."</td>
       <td>".$row->TimeB_48."</td>
       <td>".$row->SelectA_49."</td>
       <td>".$row->TimeA_49."</td>
       <td>".$row->Confidence_49."</td>
       <td>".$row->SelectB_49."</td>
       <td>".$row->TimeB_49."</td>
       <td>".$row->SelectA_50."</td>
       <td>".$row->TimeA_50."</td>
       <td>".$row->Confidence_50."</td>
       <td>".$row->SelectB_50."</td>
       <td>".$row->TimeB_50."</td>
       <td>".$row->SelectA_51."</td>
       <td>".$row->TimeA_51."</td>
       <td>".$row->Confidence_51."</td>
       <td>".$row->SelectB_51."</td>
       <td>".$row->TimeB_51."</td>
       <td>".$row->SelectA_52."</td>
       <td>".$row->TimeA_52."</td>
       <td>".$row->Confidence_52."</td>
       <td>".$row->SelectB_52."</td>
       <td>".$row->TimeB_52."</td>
       <td>".$row->SelectA_53."</td>
       <td>".$row->TimeA_53."</td>
       <td>".$row->Confidence_53."</td>
       <td>".$row->SelectB_53."</td>
       <td>".$row->TimeB_53."</td>
       <td>".$row->SelectA_54."</td>
       <td>".$row->TimeA_54."</td>
       <td>".$row->Confidence_54."</td>
       <td>".$row->SelectB_54."</td>
       <td>".$row->TimeB_54."</td>
       <td>".$row->SelectA_55."</td>
       <td>".$row->TimeA_55."</td>
       <td>".$row->Confidence_55."</td>
       <td>".$row->SelectB_55."</td>
       <td>".$row->TimeB_55."</td>
       <td>".$row->SelectA_56."</td>
       <td>".$row->TimeA_56."</td>
       <td>".$row->Confidence_56."</td>
       <td>".$row->SelectB_56."</td>
       <td>".$row->TimeB_56."</td>
       <td>".$row->SelectA_57."</td>
       <td>".$row->TimeA_57."</td>
       <td>".$row->Confidence_57."</td>
       <td>".$row->SelectB_57."</td>
       <td>".$row->TimeB_57."</td>
       <td>".$row->SelectA_58."</td>
       <td>".$row->TimeA_58."</td>
       <td>".$row->Confidence_58."</td>
       <td>".$row->SelectB_58."</td>
       <td>".$row->TimeB_58."</td>
       <td>".$row->SelectA_59."</td>
       <td>".$row->TimeA_59."</td>
       <td>".$row->Confidence_59."</td>
       <td>".$row->SelectB_59."</td>
       <td>".$row->TimeB_59."</td>
       <td>".$row->SelectA_60."</td>
       <td>".$row->TimeA_60."</td>
       <td>".$row->Confidence_60."</td>
       <td>".$row->SelectB_60."</td>
       <td>".$row->TimeB_60."</td>
       <td>".$row->SelectA_61."</td>
       <td>".$row->TimeA_61."</td>
       <td>".$row->Confidence_61."</td>
       <td>".$row->SelectB_61."</td>
       <td>".$row->TimeB_61."</td>
       <td>".$row->SelectA_62."</td>
       <td>".$row->TimeA_62."</td>
       <td>".$row->Confidence_62."</td>
       <td>".$row->SelectB_62."</td>
       <td>".$row->TimeB_62."</td>
       <td>".$row->SelectA_63."</td>
       <td>".$row->TimeA_63."</td>
       <td>".$row->Confidence_63."</td>
       <td>".$row->SelectB_63."</td>
       <td>".$row->TimeB_63."</td>
       <td>".$row->SelectA_64."</td>
       <td>".$row->TimeA_64."</td>
       <td>".$row->Confidence_64."</td>
       <td>".$row->SelectB_64."</td>
       <td>".$row->TimeB_64."</td>
       <td>".$row->SelectA_65."</td>
       <td>".$row->TimeA_65."</td>
       <td>".$row->Confidence_65."</td>
       <td>".$row->SelectB_65."</td>
       <td>".$row->TimeB_65."</td>
       <td>".$row->SelectA_66."</td>
       <td>".$row->TimeA_66."</td>
       <td>".$row->Confidence_66."</td>
       <td>".$row->SelectB_66."</td>
       <td>".$row->TimeB_66."</td>
       <td>".$row->SelectA_67."</td>
       <td>".$row->TimeA_67."</td>
       <td>".$row->Confidence_67."</td>
       <td>".$row->SelectB_67."</td>
       <td>".$row->TimeB_67."</td>
       <td>".$row->SelectA_68."</td>
       <td>".$row->TimeA_68."</td>
       <td>".$row->Confidence_68."</td>
       <td>".$row->SelectB_68."</td>
       <td>".$row->TimeB_68."</td>
       <td>".$row->SelectA_69."</td>
       <td>".$row->TimeA_69."</td>
       <td>".$row->Confidence_69."</td>
       <td>".$row->SelectB_69."</td>
       <td>".$row->TimeB_69."</td>
       <td>".$row->SelectA_70."</td>
       <td>".$row->TimeA_70."</td>
       <td>".$row->Confidence_70."</td>
       <td>".$row->SelectB_70."</td>
       <td>".$row->TimeB_70."</td>
       <td>".$row->SelectA_71."</td>
       <td>".$row->TimeA_71."</td>
       <td>".$row->Confidence_71."</td>
       <td>".$row->SelectB_71."</td>
       <td>".$row->TimeB_71."</td>
       <td>".$row->SelectA_72."</td>
       <td>".$row->TimeA_72."</td>
       <td>".$row->Confidence_72."</td>
       <td>".$row->SelectB_72."</td>
       <td>".$row->TimeB_72."</td>
       <td>".$row->SelectA_73."</td>
       <td>".$row->TimeA_73."</td>
       <td>".$row->Confidence_73."</td>
       <td>".$row->SelectB_73."</td>
       <td>".$row->TimeB_73."</td>
       <td>".$row->SelectA_74."</td>
       <td>".$row->TimeA_74."</td>
       <td>".$row->Confidence_74."</td>
       <td>".$row->SelectB_74."</td>
       <td>".$row->TimeB_74."</td>
       <td>".$row->SelectA_75."</td>
       <td>".$row->TimeA_75."</td>
       <td>".$row->Confidence_75."</td>
       <td>".$row->SelectB_75."</td>
       <td>".$row->TimeB_75."</td>
       <td>".$row->SelectA_76."</td>
       <td>".$row->TimeA_76."</td>
       <td>".$row->Confidence_76."</td>
       <td>".$row->SelectB_76."</td>
       <td>".$row->TimeB_76."</td>
       <td>".$row->SelectA_77."</td>
       <td>".$row->TimeA_77."</td>
       <td>".$row->Confidence_77."</td>
       <td>".$row->SelectB_77."</td>
       <td>".$row->TimeB_77."</td>
       <td>".$row->SelectA_78."</td>
       <td>".$row->TimeA_78."</td>
       <td>".$row->Confidence_78."</td>
       <td>".$row->SelectB_78."</td>
       <td>".$row->TimeB_78."</td>
       <td>".$row->SelectA_79."</td>
       <td>".$row->TimeA_79."</td>
       <td>".$row->Confidence_79."</td>
       <td>".$row->SelectB_79."</td>
       <td>".$row->TimeB_79."</td>
       <td>".$row->SelectA_80."</td>
       <td>".$row->TimeA_80."</td>
       <td>".$row->Confidence_80."</td>
       <td>".$row->SelectB_80."</td>
       <td>".$row->TimeB_80."</td>
    </tr>

";

}


$EXCEL_FILE .= "</table>";

echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>";
echo $EXCEL_FILE;

?>
